In [1]:
import pandas as pd
import numpy as np
from simpledbf import Dbf5
import math

In [2]:
sixty_90 = pd.read_excel('../data/eia860/eia860a1990/GENTYPE3Y90.xls')
sixty_91 = pd.read_excel('../data/eia860/eia860a1991/GENTYPE3Y91.xls')
sixty_92 = pd.read_excel('../data/eia860/eia860a1992/TYPE392.xls')
sixty_93 = pd.read_excel('../data/eia860/eia860a1993/TYPE393.xls')
sixty_94 = pd.read_excel('../data/eia860/eia860a1994/TYPE394.xls')
sixty_95 = pd.read_excel('../data/eia860/eia860a1995/TYPE3Y95.xls')
sixty_96 = pd.read_excel('../data/eia860/eia860a1996/TYPE3Y96.xls')

In [3]:
sixty_97 = pd.read_excel('../data/eia860/eia860a1997/GENERTOR.xls')
sixty_98 = pd.read_excel('../data/eia860/eia860a1998/ExistingGenerators1998.xls',sheet_name=1)
sixty_99 = pd.read_excel('../data/eia860/eia860a1999/ExistingGenerators1999.xls',sheet_name=1)
sixty_00 = pd.read_excel('../data/eia860/eia860a2000/ExistingGenerators2000.xls',sheet_name=1)

In [4]:
dbf = Dbf5('../data/eia860/eia8602001/GENY01.dbf')
sixty_01 = dbf.to_dataframe()
dbf = Dbf5('../data/eia860/eia8602002/GENY02.dbf')
sixty_02 = dbf.to_dataframe()
dbf = Dbf5('../data/eia860/eia8602003/GENY03.dbf')
sixty_03 = dbf.to_dataframe()

In [5]:
sixty_04 = pd.read_excel('../data/eia860/eia8602004/GenY04.xls')
sixty_05 = pd.read_excel('../data/eia860/eia8602005/GenY05.xls')
sixty_06 = pd.read_excel('../data/eia860/eia8602006/GenY06.xls')
sixty_07 = pd.read_excel('../data/eia860/eia8602007/GenY07.xls')
sixty_08 = pd.read_excel('../data/eia860/eia8602008/GenY08.xls')

In [6]:
sixty_09 = pd.read_excel('../data/eia860/eia8602009/GeneratorY09.xls',sheet_name=0)
sixty_10 = pd.read_excel('../data/eia860/eia8602010/GeneratorsY2010.xls',sheet_name=0)
sixty_11 = pd.read_excel('../data/eia860/eia8602011/GeneratorY2011.xlsx',sheet_name=0)
sixty_12 = pd.read_excel('../data/eia860/eia8602012/GeneratorY2012.xlsx',sheet_name=0)

In [7]:
sixty_13 = pd.read_excel('../data/eia860/eia8602013/3_1_Generator_Y2013.xlsx',sheet_name=0)
sixty_14 = pd.read_excel('../data/eia860/eia8602014/3_1_Generator_Y2014.xlsx',sheet_name=0)
sixty_15 = pd.read_excel('../data/eia860/eia8602015/3_1_Generator_Y2015.xlsx',sheet_name=0)
sixty_16 = pd.read_excel('../data/eia860/eia8602016/3_1_Generator_Y2016.xlsx',sheet_name=0)
sixty_17 = pd.read_excel('../data/eia860/eia8602017/3_1_Generator_Y2017.xlsx',sheet_name=0)
sixty_18 = pd.read_excel('../data/eia860/eia8602018/3_1_Generator_Y2018.xlsx',sheet_name=0)
sixty_19 = pd.read_excel('../data/eia860/eia8602019/3_1_Generator_Y2019.xlsx',sheet_name=0)

In [8]:
sixone_90_1 = pd.read_excel('../data/eia861/f86190/F861TYP1.xls')
sixone_90_2 = pd.read_excel('../data/eia861/f86190/F861TYP2.xls')
sixone_91_1 = pd.read_excel('../data/eia861/f86191/F861TYP1.xls')
sixone_91_2 = pd.read_excel('../data/eia861/f86191/F861TYP2.xls')
sixone_92_1 = pd.read_excel('../data/eia861/f86192/F861TYP1.xls')
sixone_93_1 = pd.read_excel('../data/eia861/f86193/F861TYP1.xls')
sixone_94_1 = pd.read_excel('../data/eia861/f86194/F861TYP1.xls')
sixone_95_1 = pd.read_excel('../data/eia861/f86195/F861TYP1.xls')
sixone_96_1 = pd.read_excel('../data/eia861/f86196/F861TYP1.xls')
sixone_97_1 = pd.read_excel('../data/eia861/f86197/F861TYP1.xls')
sixone_98_1 = pd.read_excel('../data/eia861/f86198/F861TYP1.xls')
sixone_99_1 = pd.read_excel('../data/eia861/f86199/File1.xls')
sixone_00_1 = pd.read_excel('../data/eia861/f86100/FILE1.xls')
sixone_01_1 = pd.read_excel('../data/eia861/f86101/2001/file1.xls',sheet_name=0)
sixone_02_1 = pd.read_excel('../data/eia861/f86102/2002/file1.xls',sheet_name=0)
sixone_03_1 = pd.read_excel('../data/eia861/f86103/2003/file1.xls',sheet_name=0)
sixone_04_1 = pd.read_excel('../data/eia861/f86104/2004/file1.xls',sheet_name=0)
sixone_05_1 = pd.read_excel('../data/eia861/f86105/2005/file1.xls',sheet_name=0)
sixone_06_1 = pd.read_excel('../data/eia861/f86106/file1.xls',sheet_name=0)
sixone_07_1 = pd.read_excel('../data/eia861/f86107/2007/file1_2007.xls',sheet_name=0)
sixone_08_1 = pd.read_excel('../data/eia861/f86108/2008/file1_2008.xls',sheet_name=0)
sixone_09_1 = pd.read_excel('../data/eia861/f86109/2009/file1_2009.xls',sheet_name=0)
sixone_10_1 = pd.read_excel('../data/eia861/f86110/file1_2010.xls',sheet_name=0)
sixone_11_1 = pd.read_excel('../data/eia861/f86111/file1_2011.xls',sheet_name=0)
sixone_12_1 = pd.read_excel('../data/eia861/f8612012/operational_data_2012.xls',sheet_name=0)
sixone_12_2 = pd.read_excel('../data/eia861/f8612012/Sales_Ult_Cust_2012.xlsx',sheet_name=0)
sixone_13_1 = pd.read_excel('../data/eia861/f8612013/Operational_Data_2013.xlsx',sheet_name=0)
sixone_13_2 = pd.read_excel('../data/eia861/f8612013/Sales_Ult_Cust_2013.xls',sheet_name=0)
sixone_14_1 = pd.read_excel('../data/eia861/f8612014/Operational_Data_2014.xlsx',sheet_name=0)
sixone_14_2 = pd.read_excel('../data/eia861/f8612014/Sales_Ult_Cust_2014.xls',sheet_name=0)
sixone_15_1 = pd.read_excel('../data/eia861/f8612015/Operational_Data_2015.xlsx',sheet_name=0)
sixone_15_2 = pd.read_excel('../data/eia861/f8612015/Sales_Ult_Cust_2015.xlsx',sheet_name=0)
sixone_16_1 = pd.read_excel('../data/eia861/f8612016/Operational_Data_2016.xlsx',sheet_name=0)
sixone_16_2 = pd.read_excel('../data/eia861/f8612016/Sales_Ult_Cust_2016.xlsx',sheet_name=0)
sixone_17_1 = pd.read_excel('../data/eia861/f8612017/Operational_Data_2017.xlsx',sheet_name=0)
sixone_17_2 = pd.read_excel('../data/eia861/f8612017/Sales_Ult_Cust_2017.xlsx',sheet_name=0)
sixone_18_1 = pd.read_excel('../data/eia861/f8612018/Operational_Data_2018.xlsx',sheet_name=0)
sixone_18_2 = pd.read_excel('../data/eia861/f8612018/Sales_Ult_Cust_2018.xlsx',sheet_name=0)
sixone_19_1 = pd.read_excel('../data/eia861/f8612019/Operational_Data_2019.xlsx',sheet_name=0)
sixone_19_2 = pd.read_excel('../data/eia861/f8612019/Sales_Ult_Cust_2019.xlsx',sheet_name=0)

In [9]:
def fix_names(df):
    df.columns = df.columns.str.upper()
    df.columns = df.columns.str.replace(' ', '')
    df.columns = df.columns.str.replace('-', '')
    df.columns = df.columns.str.replace('_', '')
    df.columns = df.columns.str.replace('EXISTING', '')

In [10]:
sixtys = {90:sixty_90,91:sixty_91,92:sixty_92,93:sixty_93,94:sixty_94,
         95:sixty_95,96:sixty_96,97:sixty_97,98:sixty_98,99:sixty_99,
         0:sixty_00,1:sixty_01,2:sixty_02,3:sixty_03,4:sixty_04,5:sixty_05,6:sixty_06,
         7:sixty_07,8:sixty_08,9:sixty_09,10:sixty_10,11:sixty_11,12:sixty_12,
         13:sixty_13,14:sixty_14,15:sixty_15,16:sixty_16,17:sixty_17,
         18:sixty_18,19:sixty_19}
sixtyones = {90:sixone_90_1,91:sixone_91_1,
             92:sixone_92_1,93:sixone_93_1,94:sixone_94_1
             ,95:sixone_95_1,96:sixone_96_1,97:sixone_97_1,98:sixone_98_1,99:sixone_99_1,
             0:sixone_00_1,1:sixone_01_1,2:sixone_02_1,3:sixone_03_1,4:sixone_04_1,5:sixone_05_1,6:sixone_06_1
             ,7:sixone_07_1,8:sixone_08_1,9:sixone_09_1,10:sixone_10_1,11:sixone_11_1,12:sixone_12_1,
             112:sixone_12_2,13:sixone_13_1,113:sixone_13_2,14:sixone_14_1,114:sixone_14_2
             ,15:sixone_15_1,115:sixone_15_2,16:sixone_16_1,116:sixone_16_2,17:sixone_17_1,117:sixone_17_2
             ,18:sixone_18_1,118:sixone_18_2,19:sixone_19_1,119:sixone_19_2}

In [11]:
def re_index_sixtys(sixtys=sixtys):
    for i in range(11,20):
        headers = sixtys[i].iloc[0]
        sixtys[i] = pd.DataFrame(sixtys[i].values[1:], columns=headers)
re_index_sixtys()

def re_index_sixtyones(sixtyones=sixtyones):
    for item in sixtyones.items():
        if (item[0] >= 12 and item[0]<90) or (item[0] >=100 and item[0]<900):
            headers = sixtyones[item[0]].iloc[1]
            sixtyones[item[0]] = pd.DataFrame(sixtyones[item[0]].values[2:], columns=headers)
        elif (item[0]==10):
            headers = sixtyones[item[0]].iloc[6]
            sixtyones[item[0]] = pd.DataFrame(sixtyones[item[0]].values[7:], columns=headers)
        elif (item[0]==11):
            headers = sixtyones[item[0]].iloc[7]
            sixtyones[item[0]] = pd.DataFrame(sixtyones[item[0]].values[8:], columns=headers)
re_index_sixtyones()

In [12]:
for frame in sixtys.values():
    fix_names(frame)
for frame in sixtyones.values():
    fix_names(frame)

In [13]:
# for item in sixtyones.items():
#         if (item[0] >= 12 and item[0]<90) or (item[0] >=100 and item[0]<900):
#             headers = sixtyones[item[0]].iloc[1]
#             sixtyones[item[0]] = pd.DataFrame(sixtyones[item[0]].values[2:], columns=headers)

In [14]:
def only_operating(df_dict,vals=['OP']):
    for item in df_dict.items():
        if 'STATUSCODE' in item[1].columns:
            sixty_op = item[1][item[1]['STATUSCODE'].isin(vals)]
            sixty_null = item[1][item[1]['STATUSCODE'].isnull()]
            sixty_ap = sixty_op.append(sixty_null)
            df_dict[item[0]] = sixty_ap

In [15]:
print(sixty_92.shape)
only_operating(sixtys)
print(sixtys[92].shape)

(15028, 49)
(13461, 49)

In [16]:
for frame in sixtys.items():
     if frame[0] >= 90 and frame[0] <= 92:
        print(str(frame[0]) + '\n')
        print(frame[1].columns)

90

Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'STARTUPFUEL3', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'NAMEPLATECAPACITY.1', 'STATUSCODE.1', 'RETIRE/CANCELMONTH',
       'RETIRE/CANCELYEAR', 'ORIGINALINSERMN.', 'CURRENTINSERMN.',
       'CURRENTINSERMN..1', 'CURRENTINSERYR.', 'CANCEL/DELAYREASON1',
       'CANCEL/DELAYREASON2', 'CANCEL/DELAYREASON3', 'ENERGYSOURCE1.1',
       'ENERGYSOURCE2.1', 'ENERGYSOURCE3.1', 'SUMMERCAPABILITY.1',
       'WINTERCAPABILITY.1', 'DESIGNELECT.RATING', 'STARTOPERATIONMONTH',
       'STARTOPERATIONYEAR', 'ESTSUMMERCAPABILITY', 'ESTWINTERCAPABILITY',
       'FIRSTELECT.FLAG', 'SUMMERCAPABILITYFLAG', 'WINTERCAPABILITYFLAG',
       'NEWMOVER', 'NOTESFLAG', 'NOTES', 'EIA759STATUS', 'EIA759NAMEPLATE'],
      dtype='object')
91

Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'STARTUPFUEL3', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'NAMEPLATECAPACITY.1', 'STATUSCODE.1', 'RETIRE/CANCELMONTH',
       'RETIRE/CANCELYEAR', 'ORIGINALINSERMN.', 'CURRENTINSERMN.',
       'CURRENTINSERMN..1', 'CURRENTINSERYR.', 'CANCEL/DELAYREASON1',
       'CANCEL/DELAYREASON2', 'CANCEL/DELAYREASON3', 'ENERGYSOURCE1.1',
       'ENERGYSOURCE2.1', 'ENERGYSOURCE3.1', 'SUMMERCAPABILITY.1',
       'WINTERCAPABILITY.1', 'DESIGNELECT.RATING', 'STARTOPERATIONMONTH',
       'STARTOPERATIONYEAR', 'ESTSUMMERCAPABILITY', 'ESTWINTERCAPABILITY',
       'FIRSTELECT.FLAG', 'SUMMERCAPABILITYFLAG', 'WINTERCAPABILITYFLAG',
       'NEWMOVER', 'NOTESFLAG', 'NOTES', 'EIA759STATUS', 'EIA759NAMEPLATE'],
      dtype='object')
92

Index(['GENRECTYPE', 'MULTIGENUN', 'UTILCODE', 'PLNTCODE', 'GENCODE',
       'PRIMEMOVER', 'NAMEPLATE', 'SERVICETYP', 'STATUSCODE', 'INSERVMTH',
       'INSERVYR', 'STUPFUEL1', 'STUPFUEL2', 'STUPFUEL3', 'OPENSRC1',
       'OPENSRC2', 'OPENSCR3', 'HEATRATE', 'OPSUMCAP', 'OPWINCAP',
       'PRNAMEPLAT', 'PRSTATUSCD', 'RETIREMTH', 'RETIREYR', 'ORINSERVMT',
       'ORINSERVYR', 'CUINSERVMT', 'CUINSERVYR', 'CANREASON1', 'CANREASON2',
       'CANREASON3', 'PRENSRC1', 'PRENSRC2', 'PRENSRC3', 'PRSUMCAP',
       'PRWINCAP', 'ELECRATE', 'STOPERMTH', 'STOPERYR', 'ESTSUMCAP',
       'ESTWINCAP', 'FIRSTELFLG', 'SUMCAPFLG', 'WINCAPFLG', 'NEWMOVER',
       'NOTESFLAG', 'NOTES', 'EIA759STAT', 'EIA759NMPL'],
      dtype='object')

In [17]:
def add_data_year(df_dict):
    for item in df_dict.items():
        if item[0] >= 90:
            item[1]['DATAYEAR'] = 1900 + item[0]
        elif item[0] >= 100:
            item[1]['DATAYEAR'] = 2000 + item[0] - 100
        else:
            item[1]['DATAYEAR'] = 2000 + item[0]
add_data_year(sixtys)
add_data_year(sixtyones)

In [18]:
sixtys_cleaned = {}
for item in sixtys.items():
    sixtys_cleaned[item[0]] = item[1].rename(columns={'STATUS':'STATUSCODE',"GENRECTYPE": "GENERATORRECORDTYPE", "MULTIGENUN": "MULTIGENERATORUNIT",
                           "UTILCODE": "UTILITYCODE","PLNTCODE":"PLANTCODE","NAMEPLATE":"NAMEPLATECAPACITY",
                           'GENCODE':'GENERATORCODE', 'ENSOURCE1':'ENERGYSOURCE1', 'ENSOURCE2':'ENERGYSOURCE2', 'ENSOURCE3':'ENERGYSOURCE3',
                           'EIAUTILITYCODE':'UTILITYCODE','GENERATORID':'GENERATORCODE', 'OPERATINGMONTH':'INSERVICEMONTH', 'OPERATINGYEAR':'INSERVICEYEAR',
                           'INSVYEAR':'INSERVICEYEAR','INSVMONTH':'INSERVICEMONTH',
                          'SERVICETYP':'SERVICETYPE', 'INSERVMTH':'INSERVICEMONTH','INSERVYR':'INSERVICEYEAR','STUPFUEL1':'STARTUPFUEL1',
                          'STUPFUEL2':'STARTUPFUEL2','STUPFUEL3':'STARTUPFUEL3','OPENSRC1':'ENERGYSOURCE1',
                          'OPENSRC2':'ENERGYSOURCE2','OPENSRC3':'ENERGYSOURCE3',
                            'ENSOURCE1':'ENERGYSOURCE1','ENSOURCE2':'ENERGYSOURCE2','ENSOURCE3':'ENERGYSOURCE3',
                           'SUMMCAP':'SUMMERCAPABILITY','WINTCAP':'WINTERCAPABILITY',
                           'OPSUMCAP':'SUMMERCAPABILITY','OPWINCAP':'WINTERCAPABILITY',
                            'NAMEPLATECAPACITY(MW)':'NAMEPLATECAPACITY', 'SUMMERCAPACITY(MW)':'SUMMERCAPACITY', 'WINTERCAPACITY(MW)':'WINTERCAPACITY'
                          ,'MODTRANS1':'STARTUPFUEL1','MODTRANS2':'STARTUPFUEL2','MODTRANS2':'STARTUPFUEL2',
                          'ENERGYSCE1':'ENERGYSOURCE1','ENERGYSCE2':'ENERGYSOURCE2','ENERGYSCE3':'ENERGYSOURCE3',"UTILITYID":"UTILITYCODE"})
sixtyones_cleaned = {}
for item in sixtyones.items():
     if  (item[0] >=100 and item[0]<900):
        if 'BACODE' in item[1].columns:
            item[1].drop(columns=['BACODE'],inplace=True)
        if 'SHORTFORM' in item[1].columns:
            item[1].drop(columns=['SHORTFORM'],inplace=True)
        cols=pd.Series(item[1].columns)

        for dup in cols[cols.duplicated()].unique(): 
            cols[cols[cols == dup].index.values.tolist()] = [dup + '.' + str(i) if i != 0 else dup for i in range(sum(cols == dup))]

        item[1].columns=list(cols)
        sixtyones[item[0]] = item[1].rename(columns={'THOUSANDSDOLLARS':'RESIDENTIALREVENUE','THOUSANDDOLLARS':'RESIDENTIALREVENUE','MEGAWATTHOURS':'RESIDENTIALSALES','COUNT':'RESIDENTIALCUSTOMERS',
                                                    'THOUSANDSDOLLARS.1':'COMMERCIALREVENUE','THOUSANDDOLLARS.1':'COMMERCIALREVENUE','MEGAWATTHOURS.1':'COMMERCIALSALES','COUNT.1':'COMMERCIALCUSTOMERS',
                                                    'THOUSANDSDOLLARS.2':'INDUSTRIALREVENUE','THOUSANDDOLLARS.2':'INDUSTRIALREVENUE','MEGAWATTHOURS.2':'INDUSTRIALSALES','COUNT.2':'INDUSTRIALCUSTOMERS',
                                                    'THOUSANDSDOLLARS.3':'TRANSPORTREVENUE','THOUSANDDOLLARS.3':'TRANSPORTREVENUE','MEGAWATTHOURS.3':'TRANSPORTSALES','COUNT.3':'TRANSPORTCUSTOMERS',
                                                    'THOUSANDSDOLLARS.4':'TOTALREVENUE','THOUSANDDOLLARS.4':'TOTALREVENUE','MEGAWATTHOURS.4':'TOTALSALES','COUNT.4':'TOTALCUSTOMERS'})

for item in sixtyones.items():
    sixtyones_cleaned[item[0]] = item[1].rename(columns={"UTILCODE": "UTILITYCODE","UTILITYID":"UTILITYCODE","UTILITYNUMBER":"UTILITYCODE","MAILSTATE":"STATE","SUMPKLOAD":"SUMMERPEAKDEMAND","WINPKLOAD":"WINTERPEAKDEMAND",
                                                        "SUMMERPEAK":"SUMMERPEAKDEMAND","WINTERPEAK":"WINTERPEAKDEMAND","NETGEN":"NETGENERATION","REVTOTAL":"TOTALREVENUE","TOTSOURCE":"TOTALSALES",
                                                         "TOTALSOURCES":"TOTALSALES","TOTALSOURCE":"TOTALSALES","TOTALREVENUES":"TOTALREVENUE","PEAKDEMANDSUMMER":"SUMMERPEAKDEMAND","PEAKDEMANDWINTER":"WINTERPEAKDEMAND",'UTILNAME':'UTILITYNAME',
                                                        "OWNERSHIPTYPE":"OWNERSHIP"})

In [19]:
for frame in sixtys_cleaned.items():
#      if frame[0] >= 90 and frame[0] <= 99:
        print(str(frame[0]))
        print(frame[1].columns)
        print(str(len(frame[1].columns)) + '\n')

90
Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'STARTUPFUEL3', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'NAMEPLATECAPACITY.1', 'STATUSCODE.1', 'RETIRE/CANCELMONTH',
       'RETIRE/CANCELYEAR', 'ORIGINALINSERMN.', 'CURRENTINSERMN.',
       'CURRENTINSERMN..1', 'CURRENTINSERYR.', 'CANCEL/DELAYREASON1',
       'CANCEL/DELAYREASON2', 'CANCEL/DELAYREASON3', 'ENERGYSOURCE1.1',
       'ENERGYSOURCE2.1', 'ENERGYSOURCE3.1', 'SUMMERCAPABILITY.1',
       'WINTERCAPABILITY.1', 'DESIGNELECT.RATING', 'STARTOPERATIONMONTH',
       'STARTOPERATIONYEAR', 'ESTSUMMERCAPABILITY', 'ESTWINTERCAPABILITY',
       'FIRSTELECT.FLAG', 'SUMMERCAPABILITYFLAG', 'WINTERCAPABILITYFLAG',
       'NEWMOVER', 'NOTESFLAG', 'NOTES', 'EIA759STATUS', 'EIA759NAMEPLATE',
       'DATAYEAR'],
      dtype='object')
50

91
Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'STARTUPFUEL3', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'NAMEPLATECAPACITY.1', 'STATUSCODE.1', 'RETIRE/CANCELMONTH',
       'RETIRE/CANCELYEAR', 'ORIGINALINSERMN.', 'CURRENTINSERMN.',
       'CURRENTINSERMN..1', 'CURRENTINSERYR.', 'CANCEL/DELAYREASON1',
       'CANCEL/DELAYREASON2', 'CANCEL/DELAYREASON3', 'ENERGYSOURCE1.1',
       'ENERGYSOURCE2.1', 'ENERGYSOURCE3.1', 'SUMMERCAPABILITY.1',
       'WINTERCAPABILITY.1', 'DESIGNELECT.RATING', 'STARTOPERATIONMONTH',
       'STARTOPERATIONYEAR', 'ESTSUMMERCAPABILITY', 'ESTWINTERCAPABILITY',
       'FIRSTELECT.FLAG', 'SUMMERCAPABILITYFLAG', 'WINTERCAPABILITYFLAG',
       'NEWMOVER', 'NOTESFLAG', 'NOTES', 'EIA759STATUS', 'EIA759NAMEPLATE',
       'DATAYEAR'],
      dtype='object')
50

92
Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'STARTUPFUEL3', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'OPENSCR3', 'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'PRNAMEPLAT', 'PRSTATUSCD', 'RETIREMTH', 'RETIREYR', 'ORINSERVMT',
       'ORINSERVYR', 'CUINSERVMT', 'CUINSERVYR', 'CANREASON1', 'CANREASON2',
       'CANREASON3', 'PRENSRC1', 'PRENSRC2', 'PRENSRC3', 'PRSUMCAP',
       'PRWINCAP', 'ELECRATE', 'STOPERMTH', 'STOPERYR', 'ESTSUMCAP',
       'ESTWINCAP', 'FIRSTELFLG', 'SUMCAPFLG', 'WINCAPFLG', 'NEWMOVER',
       'NOTESFLAG', 'NOTES', 'EIA759STAT', 'EIA759NMPL', 'DATAYEAR'],
      dtype='object')
50

93
Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'STARTUPFUEL3', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'OPENSCR3', 'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'PRNAMEPLAT', 'PRSTATUSCD', 'RETIREMTH', 'RETIREYR', 'ORINSERVMT',
       'ORINSERVYR', 'CUINSERVMT', 'CUINSERVYR', 'CANREASON1', 'CANREASON2',
       'CANREASON3', 'PRENSRC1', 'PRENSRC2', 'PRENSRC3', 'PRSUMCAP',
       'PRWINCAP', 'ELECRATE', 'STOPERMTH', 'STOPERYR', 'ESTSUMCAP',
       'ESTWINCAP', 'FIRSTELFLG', 'SUMCAPFLG', 'WINCAPFLG', 'NEWMOVER',
       'NOTESFLAG', 'NOTES', 'EIA759STAT', 'EIA759NMPL', 'DATAYEAR'],
      dtype='object')
50

94
Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'STARTUPFUEL3', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'OPENSCR3', 'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'PRNAMEPLAT', 'PRSTATUSCD', 'RETIREMTH', 'RETIREYR', 'ORINSERVMT',
       'ORINSERVYR', 'CUINSERVMT', 'CUINSERVYR', 'CANREASON1', 'CANREASON2',
       'CANREASON3', 'PRENSRC1', 'PRENSRC2', 'PRENSRC3', 'PRSUMCAP',
       'PRWINCAP', 'ELECRATE', 'STOPERMTH', 'STOPERYR', 'ESTSUMCAP',
       'ESTWINCAP', 'FIRSTELFLG', 'SUMCAPFLG', 'WINCAPFLG', 'NEWMOVER',
       'NOTESFLAG', 'NOTES', 'EIA759STAT', 'EIA759NMPL', 'DATAYEAR'],
      dtype='object')
50

95
Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SERVICETYPE',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'FILLER1', 'ENERGYSOURCE1', 'ENERGYSOURCE2', 'FILLER2',
       'HEATRATE', 'SUMMERCAPABILITY', 'WINTERCAPABILITY', 'PRNAMEPLAT',
       'PRSTATUSCD', 'RETIREMTH', 'RETIREYR', 'ORINSERVMT', 'ORINSERVYR',
       'CUINSERVMT', 'CUINSERVYR', 'PMODTRANS1', 'PMODTRANS2', 'PRENSRC1',
       'PRENSRC2', 'FILLER3', 'PRSUMCAP', 'PRWINCAP', 'ELECRATE', 'STOPERMTH',
       'STOPERYR', 'ESTSUMCAP', 'ESTWINCAP', 'FIRSTELFLG', 'SUMCAPFLG',
       'WINCAPFLG', 'NEWMOVER', 'NOTESFLAG', 'NOTES', 'EIA759STAT',
       'EIA759NMPL', 'DATAYEAR'],
      dtype='object')
49

96
Index(['GENERATORRECORDTYPE', 'MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'NAMEPLATECAPACITY', 'OWNERSHIPT',
       'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1',
       'STARTUPFUEL2', 'ENERGYSOURCE1', 'ENERGYSOURCE2', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'PRNAMEPLAT', 'PRSTATUSCD', 'RETIREMTH', 'RETIREYR',
       'ORINSERVMT', 'ORINSERVYR', 'CUINSERVMT', 'CUINSERVYR', 'PMODTRANS1',
       'PMODTRANS2', 'PRENSRC1', 'PRENSRC2', 'PRSUMCAP', 'PRWINCAP',
       'ELECRATE', 'STOPERMTH', 'STOPERYR', 'ESTSUMCAP', 'ESTWINCAP',
       'FIRSTELFLG', 'SUMCAPFLG', 'WINCAPFLG', 'NEWMOVER', 'NOTESFLAG',
       'NOTES', 'EIA759STAT', 'EIA759NMPL', 'DATAYEAR'],
      dtype='object')
45

97
Index(['MULTIGENERATORUNIT', 'UTILITYCODE', 'PLANTCODE', 'GENERATORCODE',
       'PRIMEMOVER', 'NAMEPLATECAPACITY', 'OWNERSHIPT', 'STATUSCODE',
       'INSERVICEMONTH', 'INSERVICEYEAR', 'STARTUPFUEL1', 'STARTUPFUEL2',
       'ENERGYSOURCE1', 'ENERGYSOURCE2', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'PRNAMEPLAT', 'PRSTATUSCD', 'RETIREMTH', 'RETIREYR',
       'ORINSERVMT', 'ORINSERVYR', 'CUINSERVMT', 'CUINSERVYR', 'PMODTRANS1',
       'PMODTRANS2', 'PRENSRC1', 'PRENSRC2', 'PRSUMCAP', 'PRWINCAP',
       'ESTSUMCAP', 'ESTWINCAP', 'SUMCAPFLG', 'WINCAPFLG', 'NEWMOVER', 'NOTES',
       'DATAYEAR'],
      dtype='object')
37

98
Index(['YEAR', 'UTILITYCODE', 'PLANTCODE', 'GENERATORCODE', 'OWNERSHIP',
       'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'ENERGYSOURCE1', 'TRANSPORTATION1', 'ENERGYSOURCE2',
       'TRANSPORTATION2', 'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR',
       'RETIREMENTMONTH', 'RETIREMENTYEAR', 'UNITCODE', 'SUMMERESTIMATIONFLAG',
       'WINTERESTIMATIONFLAG', 'PROPOSEDSTATUS', 'EFFECTIVEMONTH',
       'EFFECTIVEYEAR', 'CURRENTMONTH', 'CURRENTYEAR', 'PROPOSEDENERGYSOURCE1',
       'PROPOSEDENERGYSOURCE2', 'PROPOSEDTRANSPORTATION1',
       'PROPOSEDTRANSPORTATION2', 'PROPOSEDNAMEPLATE',
       'PROPOSEDSUMMERCAPABILITY', 'PROPOSEDWINTERCAPABILITY',
       'SUMMERESTIMATEDCAPABILITY', 'WINTERESTIMATEDCAPABILITY', 'DATAYEAR'],
      dtype='object')
36

99
Index(['YEAR', 'UTILITYCODE', 'PLANTCODE', 'GENERATORCODE', 'OWNERSHIP',
       'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'ENERGYSOURCE1', 'TRANSPORTATION1', 'ENERGYSOURCE2',
       'TRANSPORTATION2', 'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR',
       'RETIREMENTMONTH', 'RETIREMENTYEAR', 'UNITCODE', 'SUMMERESTIMATIONFLAG',
       'WINTERESTIMATIONFLAG', 'PROPOSEDSTATUS', 'EFFECTIVEMONTH',
       'EFFECTIVEYEAR', 'CURRENTMONTH', 'CURRENTYEAR', 'PROPOSEDENERGYSOURCE1',
       'PROPOSEDENERGYSOURCE2', 'PROPOSEDTRANSPORTATION1',
       'PROPOSEDTRANSPORTATION2', 'PROPOSEDNAMEPLATE',
       'PROPOSEDSUMMERCAPABILITY', 'PROPOSEDWINTERCAPABILITY',
       'SUMMERESTIMATEDCAPABILITY', 'WINTERESTIMATEDCAPABILITY', 'DATAYEAR'],
      dtype='object')
36

0
Index(['YEAR', 'UTILITYCODE', 'PLANTCODE', 'GENERATORCODE', 'OWNERSHIP',
       'PRIMEMOVER', 'NAMEPLATECAPACITY', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'ENERGYSOURCE1', 'TRANSPORATION1', 'ENERGYSOURCE2',
       'TRANSPORATION2', 'STATUSCODE', 'INSERVICEMONTH', 'INSERVICEYEAR',
       'RETIREMENTMONTH', 'RETIREMENTYEAR', 'UNITCODE', 'SUMMERESTIMATIONFLAG',
       'WINTERESTIMATIONFLAG', 'DATAYEAR'],
      dtype='object')
22

1
Index(['UTILITYCODE', 'PLANTCODE', 'GENERATORCODE', 'OWNER', 'PRIMEMOVER',
       'NAMEPLATECAPACITY', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'SUMCAPGLG', 'WINCAPFLG', 'ENERGYSOURCE1', 'TRANSMODE1',
       'ENERGYSOURCE2', 'TRANSMODE2', 'ENERGYSOURCE3', 'ENSOURCE4',
       'ENSOURCE5', 'ENSOURCE6', 'STATUS TUS', 'MULTIGEN', 'COGEN', 'DISTGEN',
       'INSERVICEYEAR', 'INSERVICEMONTH', 'RETIREYEAR', 'RETIREMNTH',
       'WIND IND', 'FERCCOGEN', 'FERCDOCK', 'FERCQUAL', 'FERCQULDOC',
       'FERCSMALL', 'FERCSMADOC', 'FERCWHOLE', 'FERCWHLDOC', 'FERCEXPMT',
       'FERCEXTDOC', 'DATAYEAR'],
      dtype='object')
38

2
Index(['UTILITYCODE', 'PLANTCODE', 'GENERATORCODE', 'OWNER', 'PRIMEMOVER',
       'NAMEPLATECAPACITY', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'SUMCAPFLG', 'WINCAPFLG', 'ENERGYSOURCE1', 'TRANSMODE1',
       'ENERGYSOURCE2', 'TRANSMODE2', 'ENERGYSOURCE3', 'ENSOURCE4',
       'ENSOURCE5', 'ENSOURCE6', 'STATUSCODE', 'MULTIGEN', 'COGEN', 'DISTGEN',
       'INSERVICEYEAR', 'INSERVICEMONTH', 'RETIREYEAR', 'RETIREMNTH', 'WIND',
       'FERCCOGEN', 'FERCDOCK', 'FERCQUAL', 'FERCQULDOC', 'FERCSMALL',
       'FERCSMADOC', 'FERCWHOLE', 'FERCWHLDOC', 'FERCEXPMT', 'FERCEXTDOC',
       'DATAYEAR'],
      dtype='object')
38

3
Index(['UTILITYCODE', 'PLANTCODE', 'GENERATORCODE', 'OWNER', 'PRIMEMOVER',
       'NAMEPLATECAPACITY', 'SUMMERCAPABILITY', 'WINTERCAPABILITY',
       'SUMCAPFLG', 'WINCAPFLG', 'ENERGYSOURCE1', 'TRANSMODE1',
       'ENERGYSOURCE2', 'TRANSMODE2', 'ENERGYSOURCE3', 'ENSOURCE4',
       'ENSOURCE5', 'ENSOURCE6', 'STATUSCODE', 'MULTIGEN', 'COGEN', 'DISTGEN',
       'INSERVICEYEAR', 'INSERVICEMONTH', 'RETIREYEAR', 'RETIREMNTH', 'WIND',
       'FERCCOGEN', 'FERCDOCK', 'FERCQUAL', 'FERCQULDOC', 'FERCSMALL',
       'FERCSMADOC', 'FERCWHOLE', 'FERCWHLDOC', 'FERCOTHER', 'FERCEXTDOC',
       'DATAYEAR'],
      dtype='object')
38

4
Index(['UTILNAME', 'PLNTNAME', 'STATE', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'UNITCODE', 'OWNER', 'OWNEDBYNU',
       'DELIVERPOWERTRANSGRID', 'NAMEPLATECAPACITY', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'SUMCAPFLG', 'WINCAPFLG', 'REACTIVEPOWEROUTPUT',
       'STATUSCODE', 'SYNCHRONIZEDGRID', 'INSERVICEMONTH', 'INSERVICEYEAR',
       'RETIREMONTH', 'RETIREYEAR', 'COGEN', 'DISTGEN', 'SFGSYSTEM',
       'ENERGYSOURCE1', 'ES1TRANS1', 'ES1TRANS2', 'ES1TRANS3', 'ENERGYSOURCE2',
       'ES2TRANS1', 'ES2TRANS2', 'ES2TRANS3', 'ENERGYSOURCE3', 'ENERGYSOURCE4',
       'ENERGYSOURCE5', 'ENERGYSOURCE6', 'WINDTURBINES', 'FERCQFCOGEN',
       'FERCQFDOC', 'FERCSPP', 'FERCSPPDOC', 'FERCEWG', 'FERCEWGDOC',
       'DATAYEAR'],
      dtype='object')
46

5
Index(['UTILNAME', 'PLNTNAME', 'STATE', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'UNITCODE', 'OWNER', 'OWNEDBYNU',
       'DELIVERPOWERTRANSGRID', 'NAMEPLATECAPACITY', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'SUMCAPFLG', 'WINCAPFLG', 'REACTIVEPOWEROUTPUT',
       'STATUSCODE', 'SYNCHRONIZEDGRID', 'INSERVICEMONTH', 'INSERVICEYEAR',
       'RETIREMONTH', 'RETIREYEAR', 'COGEN', 'DISTGEN', 'SFGSYSTEM',
       'ENERGYSOURCE1', 'ES1TRANS1', 'ES1TRANS2', 'ES1TRANS3', 'ENERGYSOURCE2',
       'ES2TRANS1', 'ES2TRANS2', 'ES2TRANS3', 'ENERGYSOURCE3', 'ENERGYSOURCE4',
       'ENERGYSOURCE5', 'ENERGYSOURCE6', 'WINDTURBINES', 'FERCQFCOGEN',
       'FERCQFDOC', 'FERCSPP', 'FERCSPPDOC', 'FERCEWG', 'FERCEWGDOC',
       'DATAYEAR'],
      dtype='object')
46

6
Index(['UTILNAME', 'PLNTNAME', 'STATE', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'UNITCODE', 'OWNER', 'OWNEDBYNU',
       'DELIVERPOWERTRANSGRID', 'NAMEPLATECAPACITY', 'SUMMERCAPABILITY',
       'WINTERCAPABILITY', 'SUMCAPFLG', 'WINCAPFLG', 'REACTIVEPOWEROUTPUT',
       'STATUSCODE', 'SYNCHRONIZEDGRID', 'INSERVICEMONTH', 'INSERVICEYEAR',
       'RETIREMONTH', 'RETIREYEAR', 'COGEN', 'DISTGEN', 'SFGSYSTEM',
       'ENERGYSOURCE1', 'ES1TRANS1', 'ES1TRANS2', 'ES1TRANS3', 'ENERGYSOURCE2',
       'ES2TRANS1', 'ES2TRANS2', 'ES2TRANS3', 'ENERGYSOURCE3', 'ENERGYSOURCE4',
       'ENERGYSOURCE5', 'ENERGYSOURCE6', 'WINDTURBINES', 'MULTIFUELS',
       'FERCQFCOGEN', 'FERCQFDOC', 'FERCSPP', 'FERCSPPDOC', 'FERCEWG',
       'FERCEWGDOC', 'DATAYEAR'],
      dtype='object')
47

7
Index(['UTILNAME', 'PLNTNAME', 'STATE', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'UNITCODE', 'OWNERSHIP',
       'DELIVERPOWERTRANSGRID', 'DUCTBURNERS', 'NAMEPLATECAPACITY',
       'SUMMERCAPACITY', 'WINTERCAPACITY', 'STATUSCODE', 'SYNCHRONIZEDGRID',
       'INSERVICEMONTH', 'INSERVICEYEAR', 'RETIREMENTMONTH', 'RETIREMENTYEAR',
       'COGENERATOR', 'SFGSYSTEM', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'ENERGYSOURCE4', 'ENERGYSOURCE5', 'ENERGYSOURCE6',
       'TURBINES', 'MULTIPLEFUELS', 'PLANNEDMODIFICATIONS',
       'PLANNEDUPRATESNETSUMMERCAP', 'PLANNEDUPRATESNETWINTERCAP',
       'PLANNEDUPRATESMONTH', 'PLANNEDUPRATESYEAR',
       'PLANNEDDERATESNETSUMMERCAP', 'PLANNEDDERATESNETWINTERCAP',
       'PLANNEDDERATESMONTH', 'PLANNEDDERATESYEAR', 'PLANNEDNEWPRIMEMOVER',
       'PLANNEDENERGYSOURCE1', 'PLANNEDREPOWERMONTH', 'PLANNEDREPOWERYEAR',
       'OTHERMODS', 'OTHERMODMONTH', 'OTHERMODYEAR', 'PLANNEDRETIREMENTMONTH',
       'PLANNEDRETIREMENTYEAR', 'DATAYEAR'],
      dtype='object')
49

8
Index(['UTILNAME', 'PLNTNAME', 'STATE', 'UTILITYCODE', 'PLANTCODE',
       'GENERATORCODE', 'PRIMEMOVER', 'UNITCODE', 'OWNERSHIP',
       'DELIVERPOWERTRANSGRID', 'DUCTBURNERS', 'NAMEPLATECAPACITY',
       'SUMMERCAPABILITY', 'WINTERCAPABILITY', 'STATUSCODE',
       'SYNCHRONIZEDGRID', 'INSERVICEMONTH', 'INSERVICEYEAR',
       'RETIREMENTMONTH', 'RETIREMENTYEAR', 'COGENERATOR', 'SFGSYSTEM',
       'ENERGYSOURCE1', 'ENERGYSOURCE2', 'ENERGYSOURCE3', 'ENERGYSOURCE4',
       'ENERGYSOURCE5', 'ENERGYSOURCE6', 'TURBINES', 'MULTIPLEFUELS',
       'PLANNEDMODIFICATIONS', 'PLANNEDUPRATESNETSUMMERCAP',
       'PLANNEDUPRATESNETWINTERCAP', 'PLANNEDUPRATESMONTH',
       'PLANNEDUPRATESYEAR', 'PLANNEDDERATESNETSUMMERCAP',
       'PLANNEDDERATESNETWINTERCAP', 'PLANNEDDERATESMONTH',
       'PLANNEDDERATESYEAR', 'PLANNEDNEWPRIMEMOVER', 'PLANNEDENERGYSOURCE1',
       'PLANNEDREPOWERMONTH', 'PLANNEDREPOWERYEAR', 'OTHERMODS',
       'OTHERMODMONTH', 'OTHERMODYEAR', 'PLANNEDRETIREMENTMONTH',
       'PLANNEDRETIREMENTYEAR', 'DATAYEAR'],
      dtype='object')
49

9
Index(['UTILITYCODE', 'UTILITYNAME', 'PLANTCODE', 'PLANTNAME', 'STATE',
       'COUNTY', 'GENERATORCODE', 'PRIMEMOVER', 'STATUSCODE',
       'NAMEPLATECAPACITY', 'SUMMERCAPABILITY', 'WINTERCAPABILITY', 'UNITCODE',
       'INSERVICEMONTH', 'INSERVICEYEAR', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'ENERGYSOURCE4', 'ENERGYSOURCE5', 'ENERGYSOURCE6',
       'MULTIPLEFUELS', 'DELIVERPOWERTRANSGRID', 'SYNCHRONIZEDGRID',
       'OWNERSHIP', 'TURBINES', 'COGENERATOR', 'SECTORNAME', 'SECTORNUMBER',
       'TOPPINGBOTTOMING', 'DUCTBURNERS', 'PLANNEDMODIFICATIONS',
       'PLANNEDUPRATESNETSUMMERCAP', 'PLANNEDUPRATESNETWINTERCAP',
       'PLANNEDUPRATESMONTH', 'PLANNEDUPRATESYEAR',
       'PLANNEDDERATESNETSUMMERCAP', 'PLANNEDDERATESNETWINTERCAP',
       'PLANNEDDERATESMONTH', 'PLANNEDDERATESYEAR', 'PLANNEDNEWPRIMEMOVER',
       'PLANNEDENERGYSOURCE1', 'PLANNEDREPOWERMONTH', 'PLANNEDREPOWERYEAR',
       'OTHERMODS', 'OTHERMODMONTH', 'OTHERMODYEAR', 'PLANNEDRETIREMENTMONTH',
       'PLANNEDRETIREMENTYEAR', 'SFGSYSTEM', 'PULVERIZEDCOAL', 'FLUIDIZEDBED',
       'SUBCRITICAL', 'SUPERCRITICAL', 'ULTRASUPERCRITICAL', 'CARBONCAPTURE',
       'STARTUPSOURCE1', 'STARTUPSOURCE2', 'STARTUPSOURCE3', 'STARTUPSOURCE4',
       'DATAYEAR'],
      dtype='object')
61

10
Index(['UTILITYCODE', 'UTILITYNAME', 'PLANTCODE', 'PLANTNAME', 'STATE',
       'COUNTY', 'GENERATORCODE', 'PRIMEMOVER', 'STATUSCODE',
       'NAMEPLATECAPACITY', 'SUMMERCAPABILITY', 'WINTERCAPABILITY', 'UNITCODE',
       'INSERVICEMONTH', 'INSERVICEYEAR', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'ENERGYSOURCE4', 'ENERGYSOURCE5', 'ENERGYSOURCE6',
       'MULTIPLEFUELS', 'DELIVERPOWERTRANSGRID', 'SYNCHRONIZEDGRID',
       'OWNERSHIP', 'TURBINES', 'COGENERATOR', 'SECTORNAME', 'SECTORNUMBER',
       'TOPPINGBOTTOMING', 'DUCTBURNERS', 'PLANNEDMODIFICATIONS',
       'PLANNEDUPRATESNETSUMMERCAP', 'PLANNEDUPRATESNETWINTERCAP',
       'PLANNEDUPRATESMONTH', 'PLANNEDUPRATESYEAR',
       'PLANNEDDERATESNETSUMMERCAP', 'PLANNEDDERATESNETWINTERCAP',
       'PLANNEDDERATESMONTH', 'PLANNEDDERATESYEAR', 'PLANNEDNEWPRIMEMOVER',
       'PLANNEDENERGYSOURCE1', 'PLANNEDREPOWERMONTH', 'PLANNEDREPOWERYEAR',
       'OTHERMODS', 'OTHERMODMONTH', 'OTHERMODYEAR', 'PLANNEDRETIREMENTMONTH',
       'PLANNEDRETIREMENTYEAR', 'SFGSYSTEM', 'PULVERIZEDCOAL', 'FLUIDIZEDBED',
       'SUBCRITICAL', 'SUPERCRITICAL', 'ULTRASUPERCRITICAL', 'CARBONCAPTURE',
       'STARTUPSOURCE1', 'STARTUPSOURCE2', 'STARTUPSOURCE3', 'STARTUPSOURCE4',
       'DATAYEAR'],
      dtype='object')
61

11
Index(['UTILITYCODE', 'UTILITYNAME', 'PLANTCODE', 'PLANTNAME', 'STATE',
       'COUNTY', 'GENERATORCODE', 'PRIMEMOVER', 'STATUSCODE',
       'NAMEPLATECAPACITY', 'SUMMERCAPABILITY', 'WINTERCAPABILITY', 'UNITCODE',
       'INSERVICEMONTH', 'INSERVICEYEAR', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'ENERGYSOURCE4', 'ENERGYSOURCE5', 'ENERGYSOURCE6',
       'MULTIPLEFUELS', 'DELIVERPOWERTRANSGRID', 'SYNCHRONIZEDGRID',
       'OWNERSHIP', 'TURBINES', 'COGENERATOR', 'SECTORNAME', 'SECTOR',
       'TOPPINGBOTTOMING', 'DUCTBURNERS', 'PLANNEDMODIFICATIONS',
       'PLANNEDUPRATESNETSUMMERCAP', 'PLANNEDUPRATESNETWINTERCAP',
       'PLANNEDUPRATESMONTH', 'PLANNEDUPRATESYEAR',
       'PLANNEDDERATESNETSUMMERCAP', 'PLANNEDDERATESNETWINTERCAP',
       'PLANNEDDERATESMONTH', 'PLANNEDDERATESYEAR', 'PLANNEDNEWPRIMEMOVER',
       'PLANNEDENERGYSOURCE1', 'PLANNEDREPOWERMONTH', 'PLANNEDREPOWERYEAR',
       'OTHERMODS', 'OTHERMODMONTH', 'OTHERMODYEAR', 'PLANNEDRETIREMENTMONTH',
       'PLANNEDRETIREMENTYEAR', 'SFGSYSTEM', 'PULVERIZEDCOAL', 'FLUIDIZEDBED',
       'SUBCRITICAL', 'SUPERCRITICAL', 'ULTRASUPERCRITICAL', 'CARBONCAPTURE',
       'STARTUPSOURCE1', 'STARTUPSOURCE2', 'STARTUPSOURCE3', 'STARTUPSOURCE4',
       'DATAYEAR'],
      dtype='object', name=0)
61

12
Index(['UTILITYCODE', 'UTILITYNAME', 'PLANTCODE', 'PLANTNAME', 'STATE',
       'COUNTY', 'GENERATORCODE', 'PRIMEMOVER', 'STATUSCODE',
       'NAMEPLATECAPACITY', 'SUMMERCAPACITY', 'WINTERCAPACITY', 'UNITCODE',
       'INSERVICEMONTH', 'INSERVICEYEAR', 'ENERGYSOURCE1', 'ENERGYSOURCE2',
       'ENERGYSOURCE3', 'ENERGYSOURCE4', 'ENERGYSOURCE5', 'ENERGYSOURCE6',
       'MULTIPLEFUELS', 'DELIVERPOWERTOTRANSMISSIONGRID',
       'SYNCHRONIZEDTOTRANSMISSIONGRID', 'OWNERSHIP', 'TURBINES',
       'COGENERATOR', 'SECTORNAME', 'SECTOR', 'TOPPINGORBOTTOMING',
       'DUCTBURNERS', 'PLANNEDMODIFICATIONS',
       'PLANNEDUPRATESNETSUMMERCAPACITY', 'PLANNEDUPRATESNETWINTERCAPACITY',
       'PLANNEDUPRATEMONTH', 'PLANNEDUPRATEYEAR',
       'PLANNEDDERATESNETSUMMERCAPACITY', 'PLANNEDDERATESNETWINTERCAPACITY',
       'PLANNEDDERATESMONTH', 'PLANNEDDERATESYEAR', 'PLANNEDNEWPRIMEMOVER',

In [20]:
sixtys_cleaned[99].shape

(14320, 36)

In [21]:
sixtys_agg = sixtys_cleaned[90].copy()
i = 0
for item in sixtys_cleaned.items():
    if i >=1:
        sixtys_agg = pd.concat([sixtys_agg, item[1]], sort=False,ignore_index=True).copy()
    i += 1

In [22]:
print(len(sixtys_agg.columns))
print(sixtys_agg['DATAYEAR'].value_counts())

253
2019    22731
2018    22119
2017    21438
2016    20725
2015    20069
2014    19745
2008    19558
2013    19243
2007    19060
2012    19023
2011    18530
2006    18354
2010    18150
2005    17999
2009    17876
2004    17728
2003    17366
2002    16801
2001    16029
2000    14612
1999    14320
1998    14111
1994    13615
1993    13476
1992    13461
1991    13004
1990    12731
1995    11446
1996    11396
1997    10422
Name: DATAYEAR, dtype: int64

In [23]:
sixtys_agg.to_csv('../data/aggregate_860_dirty.csv')

In [24]:
for item in sixtyones_cleaned.items():
        print(str(item[0]))
#         print(sixtyones[item[0]].head(1))
        print(sixtyones_cleaned[item[0]].columns)
        print(str(len(sixtyones[item[0]].columns)) + '\n')

90
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP', 'ASCC', 'ECAR', 'ERCOT',
       'MAIN', 'MAAC', 'MAPP', 'NPCC', 'SERC', 'SPP', 'WSCC', 'HI', 'PRTERR',
       'NERCMEMBER', 'NERCASSOC', 'NERCNONMEM', 'WINTERPEAKDEMAND',
       'OPPLNT10YR', 'GENERATION', 'TRANSMISS', 'DISTRIBUT',
       'SUMMERPEAKDEMAND', 'NETGENERATION', 'PURCHUTIL', 'PURCHNONUT',
       'NETEXCHANG', 'NETWHEELIN', 'TOTALSALES', 'SALESCONS', 'SALESRESAL',
       'ENERGYNOCH', 'ENERGYUSED', 'TOTLOSS', 'TOTDISP', 'REVCONSUM',
       'REVRESALE', 'REVOTHER', 'REVNONELEC', 'REVNONUTIL', 'TOTALREVENUE',
       'EXCHANGEIN', 'EXCHANGEOT', 'WHEELINGIN', 'WHEELNGOUT', 'OWNERSUB',
       'STCODE11', 'REV11', 'REV12', 'REV13', 'REV14', 'REV15', 'REV16',
       'MWH11', 'MWH12', 'MWH13', 'MWH14', 'MWH15', 'MWH16', 'CONSUM11',
       'CONSUM12', 'CONSUM13', 'CONSUM14', 'CONSUM15', 'CONSUM16', 'STCODE21',
       'REV21', 'REV22', 'REV23', 'REV24', 'REV25', 'REV26', 'MWH21', 'MWH22',
       'MWH23', 'MWH24', 'MWH25', 'MWH26', 'CONSUM21', 'CONSUM22', 'CONSUM23',
       'CONSUM24', 'CONSUM25', 'CONSUM26', 'DMDSDMGT', 'REVREFUNDS', 'NOTES',
       'DATAYEAR'],
      dtype='object')
96

91
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP', 'ASCC', 'ECAR', 'ERCOT',
       'MAIN', 'MAAC', 'MAPP', 'NPCC', 'SERC', 'SPP', 'WSCC', 'HI', 'PRTERR',
       'NERCMEMBER', 'NERCASSOC', 'NERCNONMEM', 'WINTERPEAKDEMAND',
       'OPPLNT10YR', 'GENERATION', 'TRANSMISS', 'DISTRIBUT',
       'SUMMERPEAKDEMAND', 'NETGENERATION', 'PURCHUTIL', 'PURCHNONUT',
       'NETEXCHANG', 'NETWHEELIN', 'TOTALSALES', 'SALESCONS', 'SALESRESAL',
       'ENERGYNOCH', 'ENERGYUSED', 'TOTLOSS', 'TOTDISP', 'REVCONSUM',
       'REVRESALE', 'REVOTHER', 'REVNONELEC', 'REVNONUTIL', 'TOTALREVENUE',
       'EXCHANGEIN', 'EXCHANGEOT', 'WHEELINGIN', 'WHEELNGOUT', 'OWNERSUB',
       'STCODE11', 'REV11', 'REV12', 'REV13', 'REV14', 'REV15', 'REV16',
       'MWH11', 'MWH12', 'MWH13', 'MWH14', 'MWH15', 'MWH16', 'CONSUM11',
       'CONSUM12', 'CONSUM13', 'CONSUM14', 'CONSUM15', 'CONSUM16', 'STCODE21',
       'REV21', 'REV22', 'REV23', 'REV24', 'REV25', 'REV26', 'MWH21', 'MWH22',
       'MWH23', 'MWH24', 'MWH25', 'MWH26', 'CONSUM21', 'CONSUM22', 'CONSUM23',
       'CONSUM24', 'CONSUM25', 'CONSUM26', 'DMDSDMGT', 'REVREFUNDS', 'NOTES',
       'DATAYEAR'],
      dtype='object')
96

92
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP', 'ASCC', 'ECAR', 'ERCOT',
       'MAIN', 'MAAC', 'MAPP', 'NPCC', 'SERC', 'SPP', 'WSCC', 'HI', 'PRTERR',
       'NERCMEMBER', 'NERCASSOC', 'NERCNONMEM', 'WINTERPEAKDEMAND',
       'OPPLNT10YR', 'GENERATION', 'TRANSMISS', 'DISTRIBUT',
       'SUMMERPEAKDEMAND', 'NETGENERATION', 'PURCHUTIL', 'PURCHNONUT',
       'NETEXCHANG', 'NETWHEELIN', 'TOTALSALES', 'SALESCONS', 'SALESRESAL',
       'ENERGYNOCH', 'ENERGYUSED', 'TOTLOSS', 'TOTDISP', 'REVCONSUM',
       'REVRESALE', 'REVOTHER', 'REVNONELEC', 'REVNONUTIL', 'TOTALREVENUE',
       'EXCHANGEIN', 'EXCHANGOUT', 'WHEELINGIN', 'WHEELNGOUT', 'OWNERSUB',
       'STCODE11', 'REV11', 'REV12', 'REV13', 'REV14', 'REV15', 'REV16',
       'MWH11', 'MWH12', 'MWH13', 'MWH14', 'MWH15', 'MWH16', 'CONSUM11',
       'CONSUM12', 'CONSUM13', 'CONSUM14', 'CONSUM15', 'CONSUM16', 'STCODE21',
       'REV21', 'REV22', 'REV23', 'REV24', 'REV25', 'REV26', 'MWH21', 'MWH22',
       'MWH23', 'MWH24', 'MWH25', 'MWH26', 'CONSUM21', 'CONSUM22', 'CONSUM23',
       'CONSUM24', 'CONSUM25', 'CONSUM26', 'DMDSDMGT', 'REVREFUND',
       'F861NOTES', 'DATAYEAR'],
      dtype='object')
96

93
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP', 'ASCC', 'ECAR', 'ERCOT',
       'MAIN', 'MAAC', 'MAPP', 'NPCC', 'SERC', 'SPP', 'WSCC', 'HI', 'PRTERR',
       'NERCMEMBER', 'NERCASSOC', 'NERCNONMEM', 'WINTERPEAKDEMAND',
       'OPPLNT10YR', 'GENERATION', 'TRANSMISS', 'DISTRIBUT',
       'SUMMERPEAKDEMAND', 'NETGENERATION', 'PURCHUTIL', 'PURCHNONUT',
       'NETEXCHANG', 'NETWHEELIN', 'TOTALSALES', 'SALESCONS', 'SALESRESAL',
       'ENERGYNOCH', 'ENERGYUSED', 'TOTLOSS', 'TOTDISP', 'REVCONSUM',
       'REVRESALE', 'REVOTHER', 'REVNONELEC', 'REVNONUTIL', 'TOTALREVENUE',
       'EXCHANGEIN', 'EXCHANGOUT', 'WHEELINGIN', 'WHEELNGOUT', 'OWNERSUB',
       'STCODE11', 'REV11', 'REV12', 'REV13', 'REV14', 'REV15', 'REV16',
       'MWH11', 'MWH12', 'MWH13', 'MWH14', 'MWH15', 'MWH16', 'CONSUM11',
       'CONSUM12', 'CONSUM13', 'CONSUM14', 'CONSUM15', 'CONSUM16', 'STCODE21',
       'REV21', 'REV22', 'REV23', 'REV24', 'REV25', 'REV26', 'MWH21', 'MWH22',
       'MWH23', 'MWH24', 'MWH25', 'MWH26', 'CONSUM21', 'CONSUM22', 'CONSUM23',
       'CONSUM24', 'CONSUM25', 'CONSUM26', 'DMDSDMGT', 'REVREFUND',
       'F861NOTES', 'DATAYEAR'],
      dtype='object')
96

94
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP', 'ASCC', 'ECAR', 'ERCOT',
       'MAIN', 'MAAC', 'MAPP', 'NPCC', 'SERC', 'SPP', 'WSCC', 'HI', 'PRTERR',
       'NERCMEMBER', 'NERCASSOC', 'NERCNONMEM', 'WINTERPEAKDEMAND',
       'OPPLNT10YR', 'GENERATION', 'TRANSMISS', 'DISTRIBUT',
       'SUMMERPEAKDEMAND', 'NETGENERATION', 'PURCHUTIL', 'PURCHNONUT',
       'NETEXCHANG', 'NETWHEELIN', 'TOTALSALES', 'SALESCONS', 'SALESRESAL',
       'ENERGYNOCH', 'ENERGYUSED', 'TOTLOSS', 'TOTDISP', 'REVCONSUM',
       'REVRESALE', 'REVOTHER', 'REVNONELEC', 'REVNONUTIL', 'TOTALREVENUE',
       'EXCHANGEIN', 'EXCHANGOUT', 'WHEELINGIN', 'WHEELNGOUT', 'OWNERSUB',
       'STCODE11', 'REV11', 'REV12', 'REV13', 'REV14', 'REV15', 'REV16',
       'MWH11', 'MWH12', 'MWH13', 'MWH14', 'MWH15', 'MWH16', 'CONSUM11',
       'CONSUM12', 'CONSUM13', 'CONSUM14', 'CONSUM15', 'CONSUM16', 'STCODE21',
       'REV21', 'REV22', 'REV23', 'REV24', 'REV25', 'REV26', 'MWH21', 'MWH22',
       'MWH23', 'MWH24', 'MWH25', 'MWH26', 'CONSUM21', 'CONSUM22', 'CONSUM23',
       'CONSUM24', 'CONSUM25', 'CONSUM26', 'DMDSDMGT', 'REVREFUND',
       'F861NOTES', 'DATAYEAR'],
      dtype='object')
96

95
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP',
       ...
       'CONSUM26', 'DMDSDMGT', 'POWERMARK', 'TRANSLOSS', 'CONTROLOP', 'EMAIL',
       'CONTROLNUM', 'REVREFUNDS', 'NOTES', 'DATAYEAR'],
      dtype='object', length=101)
101

96
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP',
       ...
       'CONSUM26', 'DMDSDMGT', 'POWERMARK', 'TRANSLOSS', 'CONTROLOP', 'EMAIL',
       'CONTROLNUM', 'REVREFUNDS', 'NOTES', 'DATAYEAR'],
      dtype='object', length=101)
101

97
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP',
       ...
       'CONSUM26', 'DMDSDMGT', 'POWERMARK', 'TRANSLOSS', 'CONTROLOP', 'EMAIL',
       'CONTROLNUM', 'REVREFUNDS', 'NOTES', 'DATAYEAR'],
      dtype='object', length=101)
101

98
Index(['UTILRECTYP', 'STSALESSW', 'UTILITYCODE', 'F861STATUS', 'UTILITYNAME',
       'FEDERAL', 'STATE', 'MUNI', 'PRIVATE', 'COOP',
       ...
       'CONSUM26', 'DMDSDMGT', 'POWERMARK', 'TRANSLOSS', 'CONTROLOP', 'EMAIL',
       'CONTROLNUM', 'REVREFUNDS', 'NOTES', 'DATAYEAR'],
      dtype='object', length=101)
101

99
Index(['UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNRCODE', 'OWNERSHIP',
       'NERCLOC', 'AK', 'ECAR', 'ERCOT', 'FRCC', 'MAAC', 'MAIN', 'MAPP',
       'NPCC', 'SERC', 'SPP', 'WSCC', 'HI', 'PR', 'CONTROLAREAOPERATOR1',
       'OPERCODE1', 'CONTROLAREAOPERATOR2', 'OPERCODE2',
       'CONTROLAREAOPERATOR3', 'OPERCODE3', 'OPERGEN', 'GENER', 'TRANSOWN',
       'TRANSBUY', 'DISTOWN', 'DISTBUY', 'WHLSALE', 'RETAILPM', 'ANCILSERV',
       'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'PMRETAIL', 'PMWHLSALE',
       'PMACT', 'UTILACT', 'NETGENERATION', 'PURCHUTIL', 'PURCHNONUTIL',
       'PURCHPM', 'EXCHNGIN', 'EXCHNGOUT', 'EXCHNGNET', 'WHEELIN', 'WHEELOUT',
       'WHEELNET', 'TRNSBYOTHRS', 'TOTALSALES', 'SALESTOCONSMERS',
       'SALESFORRESALE', 'SALESTOPWRMRKT', 'FRNSHDW/OCHRG', 'USEDBYELECDPT',
       'ENERGYLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUE', 'RESALEREVENUE',
       'REVADJUSTMENTS', 'OTHER(456)REVENUE', 'TOTALREVENUE', 'DATAYEAR'],
      dtype='object')
65

0
Index(['UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNRCODE', 'OWNERSHIP',
       'NERCLOC', 'AK', 'ECAR', 'ERCOT', 'FRCC', 'MAAC', 'MAIN', 'MAPP',
       'NPCC', 'SERC', 'SPP', 'WSCC', 'HI', 'PR', 'CONTROLAREAOPERATOR1',
       'OPERCODE1', 'CONTROLAREAOPERATOR2', 'OPERCODE2',
       'CONTROLAREAOPERATOR3', 'OPERCODE3', 'OPERGEN', 'GENER', 'TRANSOWN',
       'TRANSBUY', 'DISTOWN', 'DISTBUY', 'WHLSALE', 'RETAILPM', 'ANCILSERV',
       'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'PMRETAIL', 'PMWHLSALE',
       'NETGENERATION', 'PURCHUTIL', 'EXCHNGIN', 'EXCHNGOUT', 'EXCHNGNET',
       'WHEELIN', 'WHEELOUT', 'WHEELNET', 'TRNSBYOTHRS', 'TOTALSALES',
       'SALESTOCONSMERS', 'SALESFORRESALE', 'FRNSHDW/OCHRG', 'USEDBYELECDPT',
       'ENERGYLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUE', 'RESALEREVENUE',
       'REVADJUSTMENTS', 'OTHER(456)REVENUE', 'TOTALREVENUE', 'DATAYEAR'],
      dtype='object')
60

1
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELIN', 'WHEELOUT', 'WHEELEDNET',
       'TRANSLOSSESOTHERS', 'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE',
       'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT', 'CONSUMEDBYFACILITY',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES', 'DELIVERYREVENUE',
       'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT', 'OTHERREVENUES',
       'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
33

2
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELIN', 'WHEELOUT', 'WHEELEDNET',
       'TRANSLOSSESOTHERS', 'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE',
       'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT', 'CONSUMEDBYFACILITY',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES', 'DELIVERYREVENUE',
       'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT', 'OTHERREVENUES',
       'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
33

3
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELIN', 'WHEELOUT', 'WHEELEDNET',
       'TRANSLOSSESOTHERS', 'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE',
       'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT', 'CONSUMEDBYFACILITY',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES', 'DELIVERYREVENUE',
       'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT', 'OTHERREVENUES',
       'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
33

4
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELIN', 'WHEELOUT', 'WHEELEDNET',
       'TRANSLOSSESOTHERS', 'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE',
       'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT', 'CONSUMEDBYFACILITY',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES', 'DELIVERYREVENUE',
       'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT', 'OTHERREVENUES',
       'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
33

5
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELIN', 'WHEELOUT', 'WHEELEDNET',
       'TRANSLOSSESOTHERS', 'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE',
       'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT', 'CONSUMEDBYFACILITY',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES', 'DELIVERYREVENUE',
       'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT', 'OTHERREVENUES',
       'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
33

6
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELIN', 'WHEELOUT', 'WHEELEDNET',
       'TRANSLOSSESOTHERS', 'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE',
       'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT', 'TOTALLOSSES',
       'TOTALDISPOSITION', 'RETAILREVENUES', 'DELIVERYREVENUE',
       'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT', 'OTHERREVENUES',
       'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
32

7
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELEDRECEIVED', 'WHEELEDDELIVERED', 'WHEELEDNET',
       'TRANSMISSIONBYOTHERSLOSSES', 'TOTALSALES', 'RETAILSALES',
       'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES',
       'UNBUNDLEDREVENUES', 'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT',
       'OTHERREVENUES', 'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
32

8
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELEDRECEIVED', 'WHEELEDDELIVERED', 'WHEELEDNET',
       'TRANSMISSIONBYOTHERSLOSSES', 'TOTALSALES', 'RETAILSALES',
       'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES',
       'UNBUNDLEDREVENUES', 'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT',
       'OTHERREVENUES', 'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
32

9
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELEDRECEIVED', 'WHEELEDDELIVERED', 'WHEELEDNET',
       'TRANSMISSIONBYOTHERSLOSSES', 'TOTALSALES', 'RETAILSALES',
       'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES',
       'UNBUNDLEDREVENUES', 'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT',
       'OTHERREVENUES', 'TOTALREVENUE', 'DATATYPE', 'DATAYEAR'],
      dtype='object')
32

10
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELEDRECEIVED', 'WHEELEDDELIVERED', 'WHEELEDNET',
       'TRANSMISSIONBYOTHERSLOSSES', 'TOTALSALES', 'RETAILSALES',
       'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES',
       'UNBUNDLEDREVENUES', 'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT',
       'TRANSMISSIONREVENUES', 'OTHERREVENUES', 'TOTALREVENUE', 'DATATYPE',
       'DATAYEAR'],
      dtype='object', name=6)
33

11
Index(['YEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCLOCATION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPURCHASES', 'EXCHANGEDRECEIVED', 'EXCHANGEDDELIVERED',
       'EXCHANGEDNET', 'WHEELEDRECEIVED', 'WHEELEDDELIVERED', 'WHEELEDNET',
       'TRANSMISSIONBYOTHERSLOSSES', 'TOTALSALES', 'RETAILSALES',
       'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE', 'CONSUMEDBYRESPONDENT',
       'TOTALLOSSES', 'TOTALDISPOSITION', 'RETAILREVENUES',
       'UNBUNDLEDREVENUES', 'RESALEREVENUES', 'REVENUECREDITSANDADJUSTMENT',
       'TRANSMISSIONREVENUES', 'OTHERREVENUES', 'TOTALREVENUE', 'DATATYPE',
       'DATAYEAR'],
      dtype='object', name=7)
33

12
Index(['DATAYEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCREGION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPOWERPURCHASES', 'EXCHANGEENERGYRECEIVED',
       'EXCHANGEENERGYDELIVERED', 'NETPOWEREXCHANGED', 'WHEELEDPOWERRECEIVED',
       'WHEELEDPOWERDELIVERED', 'NETWHEELEDPOWER', 'TRANSMISSIONBYOTHERLOSSES',
       'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE',
       'CONSUMEDBYRESPONDENTWITHOUTCHARGE', 'TOTALENERGYLOSSES',
       'TOTALDISPOSITION', 'FROMRETAILSALES', 'FROMDELIVERYCUSTOMERS',
       'FROMSALESFORRESALE', 'FROMCREDITSORADJUSTMENTS', 'FROMTRANSMISSION',
       'FROMOTHER', 'TOTAL', 'DATATYPE\nO=OBSERVED\nI=IMPUTED'],
      dtype='object', name=1)
32

112
Index(['DATAYEAR', 'UTILITYCODE', 'UTILITYNAME', 'PART', 'SERVICETYPE',
       'DATATYPE\nO=OBSERVED\nI=IMPUTED', 'STATE', 'OWNERSHIP',
       'RESIDENTIALREVENUE', 'RESIDENTIALSALES', 'RESIDENTIALCUSTOMERS',
       'COMMERCIALREVENUE', 'COMMERCIALSALES', 'COMMERCIALCUSTOMERS',
       'INDUSTRIALREVENUE', 'INDUSTRIALSALES', 'INDUSTRIALCUSTOMERS',
       'TRANSPORTREVENUE', 'TRANSPORTSALES', 'TRANSPORTCUSTOMERS',
       'TOTALREVENUE', 'TOTALSALES', 'TOTALCUSTOMERS'],
      dtype='object')
23

13
Index(['DATAYEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCREGION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPOWERPURCHASES', 'EXCHANGEENERGYRECEIVED',
       'EXCHANGEENERGYDELIVERED', 'NETPOWEREXCHANGED', 'WHEELEDPOWERRECEIVED',
       'WHEELEDPOWERDELIVERED', 'NETWHEELEDPOWER', 'TRANSMISSIONBYOTHERLOSSES',
       'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE',
       'CONSUMEDBYRESPONDENTWITHOUTCHARGE', 'TOTALENERGYLOSSES',
       'TOTALDISPOSITION', 'FROMRETAILSALES', 'FROMDELIVERYCUSTOMERS',
       'FROMSALESFORRESALE', 'FROMCREDITSORADJUSTMENTS', 'FROMTRANSMISSION',
       'FROMOTHER', 'TOTAL', 'DATATYPE\nO=OBSERVED\nI=IMPUTED'],
      dtype='object', name=1)
32

113
Index(['DATAYEAR', 'UTILITYCODE', 'UTILITYNAME', 'PART', 'SERVICETYPE',
       'DATATYPE\nO=OBSERVED\nI=IMPUTED', 'STATE', 'OWNERSHIP',
       'RESIDENTIALREVENUE', 'RESIDENTIALSALES', 'RESIDENTIALCUSTOMERS',
       'COMMERCIALREVENUE', 'COMMERCIALSALES', 'COMMERCIALCUSTOMERS',
       'INDUSTRIALREVENUE', 'INDUSTRIALSALES', 'INDUSTRIALCUSTOMERS',
       'TRANSPORTREVENUE', 'TRANSPORTSALES', 'TRANSPORTCUSTOMERS',
       'TOTALREVENUE', 'TOTALSALES', 'TOTALCUSTOMERS'],
      dtype='object')
23

14
Index(['DATAYEAR', 'UTILITYCODE', 'UTILITYNAME', 'STATE', 'OWNERSHIP',
       'NERCREGION', 'SUMMERPEAKDEMAND', 'WINTERPEAKDEMAND', 'NETGENERATION',
       'WHOLESALEPOWERPURCHASES', 'EXCHANGEENERGYRECEIVED',
       'EXCHANGEENERGYDELIVERED', 'NETPOWEREXCHANGED', 'WHEELEDPOWERRECEIVED',
       'WHEELEDPOWERDELIVERED', 'NETWHEELEDPOWER', 'TRANSMISSIONBYOTHERLOSSES',
       'TOTALSALES', 'RETAILSALES', 'SALESFORRESALE', 'FURNISHEDWITHOUTCHARGE',
       'CONSUMEDBYRESPONDENTWITHOUTCHARGE', 'TOTALENERGYLOSSES',
       'TOTALDISPOSITION', 'FROMRETAILSALES', 'FROMDELIVERYCUSTOMERS',
       'FROMSALESFORRESALE', 'FROMCREDITSORADJUSTMENTS', 'FROMTRANSMISSION',
       'FROMOTHER', 'TOTAL', 'DATATYPE\nO=OBSERVED\nI=IMPUTED'],

In [25]:
sixtyones_joined = {}
for item in sixtyones_cleaned.items():
    if (item[0]>=12 and item[0]<90):
        sixtyones_joined[item[0]] = item[1].join(sixtyones_cleaned[item[0]+100],on='UTILITYCODE',rsuffix="_r")
    elif item[0]<100:
        sixtyones_joined[item[0]] = item[1]
print(sixtyones_cleaned[12].shape)
print(sixtyones_joined[12].shape)
print(sixtyones_joined.keys())
print(sixtyones_joined[12]['DATAYEAR'].value_counts())

(2190, 32)
(2190, 55)
dict_keys([90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
2012    2190
Name: DATAYEAR, dtype: int64

In [26]:
print(sixtyones_cleaned[18].shape)
sixtyones_joined[18].shape

(2307, 32)

(2307, 55)

In [27]:
sixtyones_agg = sixtyones_joined[90].copy()
i = 0
for item in sixtyones_joined.items():
    if i >=1:
        sixtyones_agg = pd.concat([sixtyones_agg, item[1]], sort=False,ignore_index=True).copy()
    i += 1

In [28]:
sixtyones_agg.to_csv('../data/aggregate_861_dirty.csv')

In [29]:
print(len(sixtyones_agg.columns))
print(sixtyones_agg['DATAYEAR'].value_counts())

215
2001    4124
1993    3423
1992    3421
2019    3358
1999    3316
2000    3290
2005    3284
2003    3282
2008    3281
2004    3281
2011    3277
2009    3276
2002    3272
2006    3272
2007    3271
2010    3268
1990    3244
1991    3234
1995    3215
1994    3207
1996    3199
1997    3191
1998    3170
2018    2307
2017    2301
2016    2286
2015    2286
2014    2249
2013    2197
2012    2190
Name: DATAYEAR, dtype: int64

In [30]:
for col in sixtyones_agg.columns:
    print(col)

UTILRECTYP
STSALESSW
UTILITYCODE
F861STATUS
UTILITYNAME
FEDERAL
STATE
MUNI
PRIVATE
COOP
ASCC
ECAR
ERCOT
MAIN
MAAC
MAPP
NPCC
SERC
SPP
WSCC
HI
PRTERR
NERCMEMBER
NERCASSOC
NERCNONMEM
WINTERPEAKDEMAND
OPPLNT10YR
GENERATION
TRANSMISS
DISTRIBUT
SUMMERPEAKDEMAND
NETGENERATION
PURCHUTIL
PURCHNONUT
NETEXCHANG
NETWHEELIN
TOTALSALES
SALESCONS
SALESRESAL
ENERGYNOCH
ENERGYUSED
TOTLOSS
TOTDISP
REVCONSUM
REVRESALE
REVOTHER
REVNONELEC
REVNONUTIL
TOTALREVENUE
EXCHANGEIN
EXCHANGEOT
WHEELINGIN
WHEELNGOUT
OWNERSUB
STCODE11
REV11
REV12
REV13
REV14
REV15
REV16
MWH11
MWH12
MWH13
MWH14
MWH15
MWH16
CONSUM11
CONSUM12
CONSUM13
CONSUM14
CONSUM15
CONSUM16
STCODE21
REV21
REV22
REV23
REV24
REV25
REV26
MWH21
MWH22
MWH23
MWH24
MWH25
MWH26
CONSUM21
CONSUM22
CONSUM23
CONSUM24
CONSUM25
CONSUM26
DMDSDMGT
REVREFUNDS
NOTES
DATAYEAR
EXCHANGOUT
REVREFUND
F861NOTES
POWERMARK
TRANSLOSS
CONTROLOP
EMAIL
CONTROLNUM
OWNRCODE
OWNERSHIP
NERCLOC
AK
FRCC
PR
CONTROLAREAOPERATOR1
OPERCODE1
CONTROLAREAOPERATOR2
OPERCODE2
CONTROLAREAOPERATOR3
OPERCODE3
OPERGEN
GENER
TRANSOWN
TRANSBUY
DISTOWN
DISTBUY
WHLSALE
RETAILPM
ANCILSERV
PMRETAIL
PMWHLSALE
PMACT
UTILACT
PURCHNONUTIL
PURCHPM
EXCHNGIN
EXCHNGOUT
EXCHNGNET
WHEELIN
WHEELOUT
WHEELNET
TRNSBYOTHRS
SALESTOCONSMERS
SALESFORRESALE
SALESTOPWRMRKT
FRNSHDW/OCHRG
USEDBYELECDPT
ENERGYLOSSES
TOTALDISPOSITION
RETAILREVENUE
RESALEREVENUE
REVADJUSTMENTS
OTHER(456)REVENUE
YEAR
NERCLOCATION
WHOLESALEPURCHASES
EXCHANGEDRECEIVED
EXCHANGEDDELIVERED
EXCHANGEDNET
WHEELEDNET
TRANSLOSSESOTHERS
RETAILSALES
FURNISHEDWITHOUTCHARGE
CONSUMEDBYRESPONDENT
CONSUMEDBYFACILITY
TOTALLOSSES
RETAILREVENUES
DELIVERYREVENUE
RESALEREVENUES
REVENUECREDITSANDADJUSTMENT
OTHERREVENUES
DATATYPE
WHEELEDRECEIVED
WHEELEDDELIVERED
TRANSMISSIONBYOTHERSLOSSES
UNBUNDLEDREVENUES
TRANSMISSIONREVENUES
NERCREGION
WHOLESALEPOWERPURCHASES
EXCHANGEENERGYRECEIVED
EXCHANGEENERGYDELIVERED
NETPOWEREXCHANGED
WHEELEDPOWERRECEIVED
WHEELEDPOWERDELIVERED
NETWHEELEDPOWER
TRANSMISSIONBYOTHERLOSSES
CONSUMEDBYRESPONDENTWITHOUTCHARGE
TOTALENERGYLOSSES
FROMRETAILSALES
FROMDELIVERYCUSTOMERS
FROMSALESFORRESALE
FROMCREDITSORADJUSTMENTS
FROMTRANSMISSION
FROMOTHER
TOTAL
DATATYPE
O=OBSERVED
I=IMPUTED
DATAYEAR_r
UTILITYCODE_r
UTILITYNAME_r
PART
SERVICETYPE
DATATYPE
O=OBSERVED
I=IMPUTED_r
STATE_r
OWNERSHIP_r
RESIDENTIALREVENUE
RESIDENTIALSALES
RESIDENTIALCUSTOMERS
COMMERCIALREVENUE
COMMERCIALSALES
COMMERCIALCUSTOMERS
INDUSTRIALREVENUE
INDUSTRIALSALES
INDUSTRIALCUSTOMERS
TRANSPORTREVENUE
TRANSPORTSALES
TRANSPORTCUSTOMERS
TOTALSALES_r
TOTALCUSTOMERS
SHORTFORM

In [31]:
type(sixtyones_agg['MUNI'][2]) == str

True

In [32]:
sixtyones_agg.shape

(91972, 215)

In [33]:
sixtyones_agg['DATAYEAR'].describe()

count    91972.000000
mean      2003.680109
std          8.425509
min       1990.000000
25%       1997.000000
50%       2003.000000
75%       2010.000000
max       2019.000000
Name: DATAYEAR, dtype: float64

In [34]:
def owntype(row):
    if row['DATAYEAR'] >= 1999:
        if row['OWNERSHIP'] == 'Municipal' or row['OWNERSHIP'] == 'MUNICIPAL':
            return 1
        elif row['OWNERSHIP'] == "COOPERATIVE" or row['OWNERSHIP'] == 'Cooperative' or row['OWNERSHIP'] == 'COOP' or row['OWNERSHIP'] == 'coop':
            return 2
        elif row['OWNERSHIP'] == 'Retail Power Marketer' or row['OWNERSHIP'] == 'Power Marketer' or row['OWNERSHIP'] == 'POWER MARKETER':
            return 3
        else:
            return 0
    else:
        if type(row['MUNI']) == str:
            return 1
        elif type(row['COOP']) == str:
            return 2
        elif type(row['PRIVATE']) == str:
            return 3
        else:
            return 0




# owntype = {'OWNERSHIP' : {'Municipal':1,'MUNICIPAL':1,'COOPERATIVE':2,'Cooperative':2,'COOP':2,'coop':2,
#           'Retail Power Marketer':3,'Power Marketer':3, 'POWER MARKETER':3}}

sixtyones_agg['OWNER_TYPE'] = sixtyones_agg.apply (lambda row: owntype(row), axis=1)
    
    
# for i in range(sixtyones_agg.shape[0]):
#     if sixtyones_agg['DATAYEAR'][i] >= 1999:
#         if sixtyones_agg['OWNERSHIP'][i] == 'Municipal' or sixtyones_agg['OWNERSHIP'][i] == 'MUNICIPAL':
#             sixtyones_agg['OWNER_TYPE'][i] = 1
#         elif sixtyones_agg['OWNERSHIP'][i] == "COOPERATIVE" or sixtyones_agg['OWNERSHIP'][i] == 'COOPERATIVE' or sixtyones_agg['OWNERSHIP'][i] == 'COOP' or sixtyones_agg['OWNERSHIP'][i] == 'coop':
#             sixtyones_agg['OWNER_TYPE'][i] = 2
#         elif sixtyones_agg['OWNERSHIP'][i] == 'Retail Power Marketer' or sixtyones_agg['OWNERSHIP'][i] == 'Power Marketer' or sixtyones_agg['OWNERSHIP'][i] == 'POWER MARKETER':
#             sixtyones_agg['OWNER_TYPE'][i] = 3
#         else:
#             sixtyones_agg['OWNER_TYPE'] = 0
#     else:
#         if type(sixtyones_agg['MUNI'][i]) == str:
#             sixtyones_agg['OWNER_TYPE'][i] = 1
#         elif type(sixtyones_agg['COOP'][i]) == str:
#             sixtyones_agg['OWNER_TYPE'][i] = 2
#         elif type(sixtyones_agg['PRIVATE'][i]) == str:
#             sixtyones_agg['OWNER_TYPE'][i] = 3
#         else:
#             sixtyones_agg['OWNER_TYPE'][i] = 0
        
# sixtyones_agg = sixtyones_agg[['UTILITYCODE'
#                                 ,'UTILITYNAME'
#                                ,'MUNI'
#                                ,'PRIVATE'
#                                ,'COOP'
#                                 ,'OWNERSHIP'
#                                 ,'MUNI'
#                                 ,'PRIVATE'
#                                 ,'COOP'
#                                 ,'WINTERPEAKDEMAND'
#                                 ,'SUMMERPEAKDEMAND'
#                                 ,'NETGENERATION'
#                                 ,'SALESTOTAL'
#                                 ,'TOTALSOURCE'
#                                 ,'TOTALCUSTOMERS'
#                                 ,'TOTALREVENUE'
#                                 ,'TOTALSALES'
#                                 ,'DATAYEAR']].copy()
# for col in sixtyones_agg.columns:
#     print(col)

In [35]:
sixtyones_agg = sixtyones_agg[['UTILITYCODE'
                                ,'UTILITYNAME'
                                ,'OWNER_TYPE'
                                ,'WINTERPEAKDEMAND'
                                ,'SUMMERPEAKDEMAND'
                                ,'NETGENERATION'
                                ,'TOTALCUSTOMERS'
                                ,'TOTALREVENUE'
                                ,'TOTALSALES'
                                ,'DATAYEAR']].copy()

In [36]:
sixtyones_agg['TOTALSALES'].value_counts().sum()

91839

In [37]:
for col in sixtys_agg.columns:
    print(col)

GENERATORRECORDTYPE
MULTIGENERATORUNIT
UTILITYCODE
PLANTCODE
GENERATORCODE
PRIMEMOVER
NAMEPLATECAPACITY
SERVICETYPE
STATUSCODE
INSERVICEMONTH
INSERVICEYEAR
STARTUPFUEL1
STARTUPFUEL2
STARTUPFUEL3
ENERGYSOURCE1
ENERGYSOURCE2
ENERGYSOURCE3
HEATRATE
SUMMERCAPABILITY
WINTERCAPABILITY
NAMEPLATECAPACITY.1
STATUSCODE.1
RETIRE/CANCELMONTH
RETIRE/CANCELYEAR
ORIGINALINSERMN.
CURRENTINSERMN.
CURRENTINSERMN..1
CURRENTINSERYR.
CANCEL/DELAYREASON1
CANCEL/DELAYREASON2
CANCEL/DELAYREASON3
ENERGYSOURCE1.1
ENERGYSOURCE2.1
ENERGYSOURCE3.1
SUMMERCAPABILITY.1
WINTERCAPABILITY.1
DESIGNELECT.RATING
STARTOPERATIONMONTH
STARTOPERATIONYEAR
ESTSUMMERCAPABILITY
ESTWINTERCAPABILITY
FIRSTELECT.FLAG
SUMMERCAPABILITYFLAG
WINTERCAPABILITYFLAG
NEWMOVER
NOTESFLAG
NOTES
EIA759STATUS
EIA759NAMEPLATE
DATAYEAR
OPENSCR3
PRNAMEPLAT
PRSTATUSCD
RETIREMTH
RETIREYR
ORINSERVMT
ORINSERVYR
CUINSERVMT
CUINSERVYR
CANREASON1
CANREASON2
CANREASON3
PRENSRC1
PRENSRC2
PRENSRC3
PRSUMCAP
PRWINCAP
ELECRATE
STOPERMTH
STOPERYR
ESTSUMCAP
ESTWINCAP
FIRSTELFLG
SUMCAPFLG
WINCAPFLG
EIA759STAT
EIA759NMPL
FILLER1
FILLER2
PMODTRANS1
PMODTRANS2
FILLER3
OWNERSHIPT
YEAR
OWNERSHIP
TRANSPORTATION1
TRANSPORTATION2
RETIREMENTMONTH
RETIREMENTYEAR
UNITCODE
SUMMERESTIMATIONFLAG
WINTERESTIMATIONFLAG
PROPOSEDSTATUS
EFFECTIVEMONTH
EFFECTIVEYEAR
CURRENTMONTH
CURRENTYEAR
PROPOSEDENERGYSOURCE1
PROPOSEDENERGYSOURCE2
PROPOSEDTRANSPORTATION1
PROPOSEDTRANSPORTATION2
PROPOSEDNAMEPLATE
PROPOSEDSUMMERCAPABILITY
PROPOSEDWINTERCAPABILITY
SUMMERESTIMATEDCAPABILITY
WINTERESTIMATEDCAPABILITY
TRANSPORATION1
TRANSPORATION2
OWNER
SUMCAPGLG
TRANSMODE1
TRANSMODE2
ENSOURCE4
ENSOURCE5
ENSOURCE6
STATUS TUS
MULTIGEN
COGEN
DISTGEN
RETIREYEAR
RETIREMNTH
WIND IND
FERCCOGEN
FERCDOCK
FERCQUAL
FERCQULDOC
FERCSMALL
FERCSMADOC
FERCWHOLE
FERCWHLDOC
FERCEXPMT
FERCEXTDOC
WIND
FERCOTHER
UTILNAME
PLNTNAME
STATE
OWNEDBYNU
DELIVERPOWERTRANSGRID
REACTIVEPOWEROUTPUT
SYNCHRONIZEDGRID
RETIREMONTH
SFGSYSTEM
ES1TRANS1
ES1TRANS2
ES1TRANS3
ES2TRANS1
ES2TRANS2
ES2TRANS3
ENERGYSOURCE4
ENERGYSOURCE5
ENERGYSOURCE6
WINDTURBINES
FERCQFCOGEN
FERCQFDOC
FERCSPP
FERCSPPDOC
FERCEWG
FERCEWGDOC
MULTIFUELS
DUCTBURNERS
SUMMERCAPACITY
WINTERCAPACITY
COGENERATOR
TURBINES
MULTIPLEFUELS
PLANNEDMODIFICATIONS
PLANNEDUPRATESNETSUMMERCAP
PLANNEDUPRATESNETWINTERCAP
PLANNEDUPRATESMONTH
PLANNEDUPRATESYEAR
PLANNEDDERATESNETSUMMERCAP
PLANNEDDERATESNETWINTERCAP
PLANNEDDERATESMONTH
PLANNEDDERATESYEAR
PLANNEDNEWPRIMEMOVER
PLANNEDENERGYSOURCE1
PLANNEDREPOWERMONTH
PLANNEDREPOWERYEAR
OTHERMODS
OTHERMODMONTH
OTHERMODYEAR
PLANNEDRETIREMENTMONTH
PLANNEDRETIREMENTYEAR
UTILITYNAME
PLANTNAME
COUNTY
SECTORNAME
SECTORNUMBER
TOPPINGBOTTOMING
PULVERIZEDCOAL
FLUIDIZEDBED
SUBCRITICAL
SUPERCRITICAL
ULTRASUPERCRITICAL
CARBONCAPTURE
STARTUPSOURCE1
STARTUPSOURCE2
STARTUPSOURCE3
STARTUPSOURCE4
SECTOR
DELIVERPOWERTOTRANSMISSIONGRID
SYNCHRONIZEDTOTRANSMISSIONGRID
TOPPINGORBOTTOMING
PLANNEDUPRATESNETSUMMERCAPACITY
PLANNEDUPRATESNETWINTERCAPACITY
PLANNEDUPRATEMONTH
PLANNEDUPRATEYEAR
PLANNEDDERATESNETSUMMERCAPACITY
PLANNEDDERATESNETWINTERCAPACITY
OTHERMODIFICATIONS
OTHERMODIFICATIONSMONTH
OTHERMODIFICATIONSYEAR
SOLIDFUELGASIFICATIONSYSTEM
PULVERIZEDCOALTECHNOLOGY
FLUIDIZEDBEDTECHNOLOGY
SUBCRITICALTECHNOLOGY
SUPERCRITICALTECHNOLOGY
ULTRASUPERCRITICALTECHNOLOGY
CARBONCAPTURETECHNOLOGY
CANBYPASSHEATRECOVERYSTEAMGENERATOR?
RTO/ISOLMPNODEDESIGNATION
RTO/ISOLOCATIONDESIGNATIONFORREPORTINGWHOLESALESALESDATATOFERC
NAMEPLATEPOWERFACTOR
MINIMUMLOAD(MW)
UPRATEORDERATECOMPLETEDDURINGYEAR
MONTHUPRATEORDERATECOMPLETED
YEARUPRATEORDERATECOMPLETED
ASSOCIATEDWITHCOMBINEDHEATANDPOWERSYSTEM
SOLIDFUELGASIFICATIONSYSTEM?
CARBONCAPTURETECHNOLOGY?
TURBINES,INVERTERS,ORHYDROKINETICBUOYS
TIMEFROMCOLDSHUTDOWNTOFULLLOAD
FLUIDIZEDBEDTECHNOLOGY?
PULVERIZEDCOALTECHNOLOGY?
STOKERTECHNOLOGY?
OTHERCOMBUSTIONTECHNOLOGY?
SUBCRITICALTECHNOLOGY?
SUPERCRITICALTECHNOLOGY?
ULTRASUPERCRITICALTECHNOLOGY?
PLANNEDNETSUMMERCAPACITYUPRATE(MW)
PLANNEDNETWINTERCAPACITYUPRATE(MW)
PLANNEDNETSUMMERCAPACITYDERATE(MW)
PLANNEDNETWINTERCAPACITYDERATE(MW)
PLANNEDDERATEMONTH
PLANNEDDERATEYEAR
PLANNEDNEWNAMEPLATECAPACITY(MW)
OTHERPLANNEDMODIFICATIONS?
COFIREFUELS?
SWITCHBETWEENOILANDNATURALGAS?
TECHNOLOGY
TURBINESORHYDROKINETICBUOYS
MULTIPLEFUELS?

In [38]:
def gentype(row):
    if row['DATAYEAR'] >= 2014:
        if row['TECHNOLOGY'] == 'Coal Integrated Gasification Combined Cycle' or row['TECHNOLOGY'] == 'Conventional Steam Coal':
            return 'coal'
        elif row['TECHNOLOGY'] == "Natural Gas Fired Combined Cycle" or row['TECHNOLOGY'] == 'Natural Gas Fired Combustion Turbine' or row['TECHNOLOGY'] == 'Natural Gas Internal Combustion Engine' \
        or row['TECHNOLOGY'] == 'Natural Gas Steam Turbine' or row['TECHNOLOGY'] == 'Natural Gas with Compressed Air Storage' or row['TECHNOLOGY'] == 'Other Natural Gas' or row['TECHNOLOGY'] == 'Other Gases'or row['TECHNOLOGY'] == 'Landfill Gas':
            return 'natural_gas'
        elif row['TECHNOLOGY'] == 'Petroleum Coke' or row['TECHNOLOGY'] == 'Petroleum Liquids':
            return 'oil'
        elif row['TECHNOLOGY'] == 'Conventional Hydroelectric' or row['TECHNOLOGY'] == 'Hydroelectric Pumped Storage':
            return 'hydroelectric'
        elif row['TECHNOLOGY'] == 'Geothermal':
            return 'geothermal'
        elif row['TECHNOLOGY'] == 'Onshore Wind Turbine' or row['TECHNOLOGY'] == 'Offshore Wind Turbine':
            return 'wind'
        elif row['TECHNOLOGY'] == 'Solar Photovoltaic' or row['TECHNOLOGY'] == 'Solar Thermal with Energy Storage' or row['TECHNOLOGY'] == 'Solar Thermal without Energy Storage':
            return 'solar'
        elif row['TECHNOLOGY'] == 'Nuclear':
            return 'nuclear'
        else:
            return 'other/unreported'
    else:
        if row['ENERGYSOURCE1'] == 'ANT' or row['ENERGYSOURCE1'] == 'BIT' or row['ENERGYSOURCE1'] == 'COL' or row['ENERGYSOURCE1'] == 'COM' or row['ENERGYSOURCE1'] == 'CWM' or row['ENERGYSOURCE1'] == 'SUB'\
        or row['ENERGYSOURCE1'] == 'LIG' or row['ENERGYSOURCE1'] == 'SGC' or row['ENERGYSOURCE1'] == 'WC' or row['ENERGYSOURCE1'] == 'RC':
            return 'coal'
        elif row['ENERGYSOURCE1'] == 'BFG' or row['ENERGYSOURCE1'] == 'NG' or row['ENERGYSOURCE1'] == 'OG' or row['ENERGYSOURCE1'] == 'GAS' or row['ENERGYSOURCE1'] == 'MTH' or row['ENERGYSOURCE1'] == 'LNG'\
        or row['ENERGYSOURCE1'] == 'LPG' or row['ENERGYSOURCE1'] == 'RG' or row['ENERGYSOURCE1'] == 'MTH' or row['ENERGYSOURCE1'] == 'SNG':
            return 'natural_gas'
        elif row['ENERGYSOURCE1'] == 'DFO' or row['ENERGYSOURCE1'] == 'JF' or row['ENERGYSOURCE1'] == 'KER' or row['ENERGYSOURCE1'] == 'PC' or row['ENERGYSOURCE1'] == 'PG' or row['ENERGYSOURCE1'] == 'RFO'\
        or row['ENERGYSOURCE1'] == 'SGP' or row['ENERGYSOURCE1'] == 'WO' or row['ENERGYSOURCE1'] == 'CRU' or row['ENERGYSOURCE1'] == 'FO1' or row['ENERGYSOURCE1'] == 'FO2' or row['ENERGYSOURCE1'] == 'FO3'\
        or row['ENERGYSOURCE1'] == 'FO4' or row['ENERGYSOURCE1'] == 'FO5' or row['ENERGYSOURCE1'] == 'FO6' or row['ENERGYSOURCE1'] == 'JF' or row['ENERGYSOURCE1'] == 'KER' or row['ENERGYSOURCE1'] == 'PET'\
        or row['ENERGYSOURCE1'] == 'TOP':
            return 'oil'
        elif row['ENERGYSOURCE1'] == 'WAT':
            return 'hydroelectric'
        elif row['ENERGYSOURCE1'] == 'GST' or row['ENERGYSOURCE1'] == 'GEO':
            return 'geothermal'
        elif row['ENERGYSOURCE1'] == 'WND':
            return 'wind'
        elif row['ENERGYSOURCE1'] == 'SUN':
            return 'solar'
        elif row['ENERGYSOURCE1'] == 'NUC' or row['ENERGYSOURCE1'] == 'UR':
            return 'nuclear'
        else:
            return 'other/unreported'

sixtys_agg['GEN_TYPE'] = sixtys_agg.apply (lambda row: gentype(row), axis=1)

In [39]:
print(sixtys_agg.shape[0])
sixtys_agg['GEN_TYPE'].value_counts()

505138

natural_gas         147411
hydroelectric       119853
oil                 118947
coal                 40783
other/unreported     38793
solar                17757
wind                 14091
geothermal            4290
nuclear               3213
Name: GEN_TYPE, dtype: int64

In [40]:
sixtys_agg = sixtys_agg[['UTILITYCODE'
                        ,'PLANTCODE'
                        ,'NAMEPLATECAPACITY'
                        ,'INSERVICEYEAR'
                        ,'GEN_TYPE'
                        ,'DATAYEAR']]
for col in sixtys_agg.columns:
    print(col)

UTILITYCODE
PLANTCODE
NAMEPLATECAPACITY
INSERVICEYEAR
GEN_TYPE
DATAYEAR

In [41]:
y = pd.get_dummies(sixtys_agg.GEN_TYPE, prefix='is')
sixtys_agg_1 = pd.concat([sixtys_agg, y],axis=1)
sixtys_agg_1 = sixtys_agg_1.drop(columns=['GEN_TYPE'])
sixtys_agg_1.head()

,UTILITYCODE,PLANTCODE,NAMEPLATECAPACITY,INSERVICEYEAR,DATAYEAR,is_coal,is_geothermal,is_hydroelectric,is_natural_gas,is_nuclear,is_oil,is_other/unreported,is_solar,is_wind
0,34,3305,1800,1941,1990,0,0,1,0,0,0,0,0,0
1,34,3305,800,1941,1990,0,0,1,0,0,0,0,0,0
2,34,3305,1100,1946,1990,0,0,0,0,0,1,0,0,0
3,189,53,1200,1926,1990,0,0,1,0,0,0,0,0,0
4,189,53,1800,1985,1990,0,0,1,0,0,0,0,0,0

In [42]:
t_int = []
t_non = []
for row in range(sixtys_agg_1.shape[0]):
    if type(sixtys_agg_1['INSERVICEYEAR'][row]) == int or type(sixtys_agg_1['INSERVICEYEAR'][row]) == float:
        t_int.append(sixtys_agg_1['INSERVICEYEAR'][row])
    else:
        t_non.append(sixtys_agg_1['INSERVICEYEAR'][row])
print(len(t_int))
print(len(t_non))
print(t_non[0])
print(type(t_non[0]))
for raw in t_non:
    int(raw)

454955
50183
1994
<class 'str'>

In [43]:
insv_mean = sixtys_agg_1['INSERVICEYEAR'].dropna()
insv_mean.astype('int')

0         1941
1         1941
2         1946
3         1926
4         1985
          ...
505133    2017
505134    2018
505135    2008
505136    2017
505137    2019
Name: INSERVICEYEAR, Length: 505118, dtype: int64

In [44]:
cap_mean = sixtys_agg_1['NAMEPLATECAPACITY'].dropna()
cap_mean.astype('int64')
cap_mean = np.round(cap_mean.mean(),0)
insv_mean = sixtys_agg_1['INSERVICEYEAR'].dropna().copy()
insv_mean = insv_mean.astype('int')
insv_mean = np.round(insv_mean.mean(),0)
fill_vals = {'NAMEPLATECAPACITY':cap_mean, 'INSERVICEYEAR':insv_mean}
sixtys_agg_1 = sixtys_agg_1.fillna(value=fill_vals)
sixtys_agg_1 = sixtys_agg_1.astype({'NAMEPLATECAPACITY': 'int','INSERVICEYEAR':'int'})
sixtys_agg_1['NAMEPLATECAPACITY'] = sixtys_agg_1['NAMEPLATECAPACITY'].replace(to_replace=0, value=cap_mean)

In [45]:
sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'NAMEPLATECAPACITY'] = sixtys_agg_1['NAMEPLATECAPACITY']/1000
sixtys_agg_1.loc[sixtys_agg_1['NAMEPLATECAPACITY'] >= 6800, 'NAMEPLATECAPACITY'] = sixtys_agg_1['NAMEPLATECAPACITY']/1000

In [46]:
sixtys_agg_1.NAMEPLATECAPACITY.value_counts()

16.837     63342
1.000      60914
2.000      37022
3.000      16717
5.000       9690
           ...
181.911        1
0.085          1
324.709        1
13.281         1
0.376          1
Name: NAMEPLATECAPACITY, Length: 2928, dtype: int64

In [47]:
sixtys_agg_1['MW_COAL'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_coal']
sixtys_agg_1['MW_GEOTHERMAL'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_geothermal']
sixtys_agg_1['MW_HYDROELECTRIC'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_hydroelectric']
sixtys_agg_1['MW_NATURAL_GAS'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_natural_gas']
sixtys_agg_1['MW_NUCLEAR'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_nuclear']
sixtys_agg_1['MW_OIL'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_oil']
sixtys_agg_1['MW_OTHER'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_other/unreported']
sixtys_agg_1['MW_SOLAR'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_solar']
sixtys_agg_1['MW_WIND'] = sixtys_agg_1['NAMEPLATECAPACITY']*sixtys_agg_1['is_wind']
sixtys_agg_1.head()

,UTILITYCODE,PLANTCODE,NAMEPLATECAPACITY,INSERVICEYEAR,DATAYEAR,is_coal,is_geothermal,is_hydroelectric,is_natural_gas,is_nuclear,...,is_wind,MW_COAL,MW_GEOTHERMAL,MW_HYDROELECTRIC,MW_NATURAL_GAS,MW_NUCLEAR,MW_OIL,MW_OTHER,MW_SOLAR,MW_WIND
0,34,3305,1.8,1941,1990,0,0,1,0,0,...,0,0.0,0.0,1.8,0.0,0.0,0.0,0.0,0.0,0.0
1,34,3305,0.8,1941,1990,0,0,1,0,0,...,0,0.0,0.0,0.8,0.0,0.0,0.0,0.0,0.0,0.0
2,34,3305,1.1,1946,1990,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,1.1,0.0,0.0,0.0
3,189,53,1.2,1926,1990,0,0,1,0,0,...,0,0.0,0.0,1.2,0.0,0.0,0.0,0.0,0.0,0.0
4,189,53,1.8,1985,1990,0,0,1,0,0,...,0,0.0,0.0,1.8,0.0,0.0,0.0,0.0,0.0,0.0

In [48]:
# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_COAL'] = sixtys_agg_1['MW_COAL']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_COAL'] <= 5000, 'MW_COAL'] = sixtys_agg_1['MW_COAL']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_GEOTHERMAL'] = sixtys_agg_1['MW_GEOTHERMAL']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_GEOTHERMAL'] <= 5000, 'MW_COAL'] = sixtys_agg_1['MW_GEOTHERMAL']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_HYDROELECTRIC'] = sixtys_agg_1['MW_HYDROELECTRIC']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_HYDROELECTRIC'] <= 5000, 'MW_HYDROELECTRIC'] = sixtys_agg_1['MW_HYDROELECTRIC']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_NATURAL_GAS'] = sixtys_agg_1['MW_NATURAL_GAS']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_NATURAL_GAS'] <= 5000, 'MW_NATURAL_GAS'] = sixtys_agg_1['MW_NATURAL_GAS']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_NUCLEAR'] = sixtys_agg_1['MW_NUCLEAR']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_NUCLEAR'] <= 5000, 'MW_NUCLEAR'] = sixtys_agg_1['MW_NUCLEAR']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_SOLAR'] = sixtys_agg_1['MW_SOLAR']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_SOLAR'] <= 5000, 'MW_SOLAR'] = sixtys_agg_1['MW_SOLAR']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_OIL'] = sixtys_agg_1['MW_OIL']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_OIL'] <= 5000, 'MW_OIL'] = sixtys_agg_1['MW_OIL']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_OTHER'] = sixtys_agg_1['MW_OTHER']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_OTHER'] <= 5000, 'MW_OTHER'] = sixtys_agg_1['MW_OTHER']/1000

# sixtys_agg_1.loc[sixtys_agg_1['DATAYEAR'] <= 1997, 'MW_WIND'] = sixtys_agg_1['MW_WIND']/1000
# sixtys_agg_1.loc[sixtys_agg_1['MW_WIND'] <= 5000, 'MW_WIND'] = sixtys_agg_1['MW_WIND']/1000

In [49]:
grouped_multiple = sixtys_agg_1.groupby(['UTILITYCODE','PLANTCODE','DATAYEAR']).agg({'INSERVICEYEAR':'max','NAMEPLATECAPACITY':'sum'
                                                                                      ,'MW_COAL':'mean','MW_GEOTHERMAL':'mean','MW_HYDROELECTRIC':'mean','MW_NATURAL_GAS':'mean','MW_NUCLEAR':'mean','MW_OIL':'mean'
                                                                                     ,'MW_OTHER':'mean','MW_SOLAR':'mean','MW_WIND':'mean'})
# grouped_multiple.columns = ['age_mean', 'age_min', 'age_max']
grouped_multiple = grouped_multiple.reset_index()

print(grouped_multiple)
print(grouped_multiple['MW_COAL'].value_counts())

       UTILITYCODE  PLANTCODE  DATAYEAR  INSERVICEYEAR  NAMEPLATECAPACITY  \
0                7    10867.0      2001           1989               62.0
1                7    10867.0      2002           1989               62.0
2                7    10867.0      2003           1989               62.0
3                7    10867.0      2004           1989               62.0
4                7    10867.0      2005           1989               62.0
...            ...        ...       ...            ...                ...
165761       63587    63924.0      2019           2008                3.0
165762       63588    63920.0      2019           2017                3.0
165763       63591    63923.0      2019           2018                5.0
165764       63594    63927.0      2019           2017                3.0
165765       63599    50736.0      2019           1991               31.0

        MW_COAL  MW_GEOTHERMAL  MW_HYDROELECTRIC  MW_NATURAL_GAS  MW_NUCLEAR  \
0          62.0            0.0               0.0             0.0         0.0
1          62.0            0.0               0.0             0.0         0.0
2          62.0            0.0               0.0             0.0         0.0
3          62.0            0.0               0.0             0.0         0.0
4          62.0            0.0               0.0             0.0         0.0
...         ...            ...               ...             ...         ...
165761      0.0            0.0               0.0             3.0         0.0
165762      0.0            0.0               0.0             3.0         0.0
165763      0.0            0.0               0.0             5.0         0.0
165764      0.0            0.0               0.0             3.0         0.0
165765      0.0            0.0               0.0             0.0         0.0

        MW_OIL  MW_OTHER  MW_SOLAR  MW_WIND
0          0.0       0.0       0.0      0.0
1          0.0       0.0       0.0      0.0
2          0.0       0.0       0.0      0.0
3          0.0       0.0       0.0      0.0
4          0.0       0.0       0.0      0.0
...        ...       ...       ...      ...
165761     0.0       0.0       0.0      0.0
165762     0.0       0.0       0.0      0.0
165763     0.0       0.0       0.0      0.0
165764     0.0       0.0       0.0      0.0
165765     0.0      31.0       0.0      0.0

[165766 rows x 14 columns]
0.000000       149735
6.000000          175
3.000000          143
7.000000          143
50.000000         124
                ...
86.025000           1
62.950000           1
5.437500            1
1418.333333         1
41.111111           1
Name: MW_COAL, Length: 1641, dtype: int64

In [50]:
sers = sixtys_agg_1.loc[:,'MW_COAL'] == 287194
for idx, val in enumerate(sers):
    if val == True:
        print(idx)
print(sixtys_agg_1.iloc[111020,:])

UTILITYCODE              17633
PLANTCODE                 1012
NAMEPLATECAPACITY      287.194
INSERVICEYEAR             1973
DATAYEAR                  1998
is_coal                      1
is_geothermal                0
is_hydroelectric             0
is_natural_gas               0
is_nuclear                   0
is_oil                       0
is_other/unreported          0
is_solar                     0
is_wind                      0
MW_COAL                287.194
MW_GEOTHERMAL                0
MW_HYDROELECTRIC             0
MW_NATURAL_GAS               0
MW_NUCLEAR                   0
MW_OIL                       0
MW_OTHER                     0
MW_SOLAR                     0
MW_WIND                      0
Name: 111020, dtype: object

In [51]:
grouped_multiple['PCT_COAL'] = grouped_multiple['MW_COAL']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_GEOTHERMAL'] = grouped_multiple['MW_GEOTHERMAL']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_HYDROELECTRIC'] = grouped_multiple['MW_HYDROELECTRIC']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_NATURAL_GAS'] = grouped_multiple['MW_NATURAL_GAS']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_NUCLEAR'] = grouped_multiple['MW_NUCLEAR']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_OIL'] = grouped_multiple['MW_OIL']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_OTHER'] = grouped_multiple['MW_OTHER']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_SOLAR'] = grouped_multiple['MW_SOLAR']/grouped_multiple['NAMEPLATECAPACITY']
grouped_multiple['PCT_WIND'] = grouped_multiple['MW_WIND']/grouped_multiple['NAMEPLATECAPACITY']
print(grouped_multiple.shape)
grouped_multiple['PCT_COAL'].value_counts()
#grouped_860 = grouped_multiple.drop(columns=['MW_COAL','MW_GEOTHERMAL','MW_HYDROELECTRIC','MW_NATURAL_GAS','MW_NUCLEAR','MW_OIL','MW_OTHER','MW_SOLAR','MW_WIND'])

(165766, 23)

0.000000    149735
0.500000      3127
1.000000      3043
0.250000      1287
0.333333      1181
             ...
0.182555         1
0.010332         1
0.117746         1
0.244209         1
0.147982         1
Name: PCT_COAL, Length: 1262, dtype: int64

In [52]:
grouped_multiple.head()

,UTILITYCODE,PLANTCODE,DATAYEAR,INSERVICEYEAR,NAMEPLATECAPACITY,MW_COAL,MW_GEOTHERMAL,MW_HYDROELECTRIC,MW_NATURAL_GAS,MW_NUCLEAR,...,MW_WIND,PCT_COAL,PCT_GEOTHERMAL,PCT_HYDROELECTRIC,PCT_NATURAL_GAS,PCT_NUCLEAR,PCT_OIL,PCT_OTHER,PCT_SOLAR,PCT_WIND
0,7,10867.0,2001,1989,62.0,62.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7,10867.0,2002,1989,62.0,62.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7,10867.0,2003,1989,62.0,62.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7,10867.0,2004,1989,62.0,62.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7,10867.0,2005,1989,62.0,62.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
grouped_multiple = grouped_multiple.groupby(['UTILITYCODE','DATAYEAR']).agg({'INSERVICEYEAR':'max','NAMEPLATECAPACITY':'sum'
                                                                                      ,'MW_COAL':'sum','MW_GEOTHERMAL':'sum','MW_HYDROELECTRIC':'sum','MW_NATURAL_GAS':'sum','MW_NUCLEAR':'sum','MW_OIL':'sum'
                                                                                     ,'MW_OTHER':'sum','MW_SOLAR':'sum','MW_WIND':'sum'
                                                                                    ,'PCT_COAL':'mean','PCT_GEOTHERMAL':'mean','PCT_HYDROELECTRIC':'mean','PCT_NATURAL_GAS':'mean'
                                                                                     ,'PCT_NUCLEAR':'mean','PCT_OIL':'mean','PCT_OTHER':'mean','PCT_SOLAR':'mean','PCT_WIND':'mean'})
grouped_multiple = grouped_multiple.reset_index()
grouped_multiple

,UTILITYCODE,DATAYEAR,INSERVICEYEAR,NAMEPLATECAPACITY,MW_COAL,MW_GEOTHERMAL,MW_HYDROELECTRIC,MW_NATURAL_GAS,MW_NUCLEAR,MW_OIL,...,MW_WIND,PCT_COAL,PCT_GEOTHERMAL,PCT_HYDROELECTRIC,PCT_NATURAL_GAS,PCT_NUCLEAR,PCT_OIL,PCT_OTHER,PCT_SOLAR,PCT_WIND
0,7.0,2001,1989,62.0,62.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,7.0,2002,1989,62.0,62.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,7.0,2003,1989,62.0,62.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,7.0,2004,1989,62.0,62.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,7.0,2005,1989,62.0,62.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70737,63587.0,2019,2008,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
70738,63588.0,2019,2017,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
70739,63591.0,2019,2018,5.0,0.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
70740,63594.0,2019,2017,3.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
70741,63599.0,2019,1991,31.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [54]:
sixtyones_agg.head()

,UTILITYCODE,UTILITYNAME,OWNER_TYPE,WINTERPEAKDEMAND,SUMMERPEAKDEMAND,NETGENERATION,TOTALCUSTOMERS,TOTALREVENUE,TOTALSALES,DATAYEAR
0,34,Abbeville City of,1,9798,12177,8706,NaN,3597,54037,1990
1,55,Aberdeen City of,1,22914,27473,0,NaN,7986,157637,1990
2,59,Abbeville City of,1,14800,25100,0,NaN,7722,102846,1990
3,84,A & N Electric Coop,2,24338,31865,139,NaN,9941,143500,1990
4,87,Ada City of,1,0,0,0,NaN,650,19032,1990

In [55]:
sixtyones_agg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91972 entries, 0 to 91971
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   UTILITYCODE       91848 non-null  object
 1   UTILITYNAME       91857 non-null  object
 2   OWNER_TYPE        91972 non-null  int64
 3   WINTERPEAKDEMAND  89084 non-null  object
 4   SUMMERPEAKDEMAND  89143 non-null  object
 5   NETGENERATION     68190 non-null  object
 6   TOTALCUSTOMERS    2290 non-null   object
 7   TOTALREVENUE      75048 non-null  object
 8   TOTALSALES        91839 non-null  object
 9   DATAYEAR          91972 non-null  int64
dtypes: int64(2), object(8)
memory usage: 7.0+ MB

In [56]:
sixtyones_agg_1 = sixtyones_agg.drop(columns=['TOTALCUSTOMERS','NETGENERATION'])

In [57]:
sixtyones_agg_1.TOTALREVENUE.value_counts()

 0.0          798
 240.0         29
 397.0         28
 270.0         28
 148.0         27
             ...
 21123.0        1
 86660.0        1
 86661.0        1
 1331849.0      1
-1.0            1
Name: TOTALREVENUE, Length: 37423, dtype: int64

In [58]:
sixtyones_agg_1.TOTALSALES.value_counts()

0.0          676
.            121
16000.0       16
17000.0       15
21000.0       15
            ...
2692371.0      1
202000         1
117482.0       1
137214.0       1
4984678.0      1
Name: TOTALSALES, Length: 79805, dtype: int64

In [59]:
sixtyones_agg_1['TOTALSALES'] = sixtyones_agg_1['TOTALSALES'].replace(to_replace='.', value=0.0)
sixtyones_agg_1['TOTALREVENUE'] = sixtyones_agg_1['TOTALREVENUE'].replace(to_replace='.', value=0.0)
sixtyones_agg_1.TOTALSALES.value_counts()

0.0          797
16000.0       16
21000.0       15
17000.0       15
2000.0        14
            ...
92449.0        1
1052675.0      1
37974.0        1
62609.0        1
327427.0       1
Name: TOTALSALES, Length: 79804, dtype: int64

In [60]:
sale_mean = sixtyones_agg_1['TOTALSALES'].dropna()
sale_mean.astype('float')
sale_mean = np.round(sale_mean.mean(),0)
# rev_mean = sixtyones_agg_1['TOTALREVENUE'].dropna().copy()
# rev_mean = rev_mean.astype('float')
# rev_mean = np.round(insv_mean.mean(),0)
fill_vals = {'TOTALSALES':sale_mean}
sixtyones_agg_1 = sixtyones_agg_1.fillna(value=fill_vals)
sixtyones_agg_1 = sixtyones_agg_1.astype({'TOTALSALES':'float'})

In [61]:
sixtyones_agg_2 = sixtyones_agg_1.copy()
sixtyones_agg_2['TOTALREVENUE'] = sixtyones_agg_2['TOTALREVENUE'].fillna(value = sixtyones_agg_2['TOTALSALES'])
sixtyones_agg_2 = sixtyones_agg_2.astype({'TOTALREVENUE':'float'})

In [62]:
sixtyones_agg_2.TOTALREVENUE.value_counts().sum()

91972

In [63]:
sixtyones_agg_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91972 entries, 0 to 91971
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   UTILITYCODE       91848 non-null  object
 1   UTILITYNAME       91857 non-null  object
 2   OWNER_TYPE        91972 non-null  int64
 3   WINTERPEAKDEMAND  89084 non-null  object
 4   SUMMERPEAKDEMAND  89143 non-null  object
 5   TOTALREVENUE      91972 non-null  float64
 6   TOTALSALES        91972 non-null  float64
 7   DATAYEAR          91972 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 5.6+ MB

In [64]:
merged = pd.merge(sixtyones_agg_2,grouped_multiple,how='inner', on=['UTILITYCODE','DATAYEAR'],suffixes=('l','r'))
merged['WINTERPEAKDEMAND'] = merged['WINTERPEAKDEMAND'].replace(to_replace='.', value=0.0)
merged['SUMMERPEAKDEMAND'] = merged['SUMMERPEAKDEMAND'].replace(to_replace='.', value=0.0)

In [65]:
merged.head()

,UTILITYCODE,UTILITYNAME,OWNER_TYPE,WINTERPEAKDEMAND,SUMMERPEAKDEMAND,TOTALREVENUE,TOTALSALES,DATAYEAR,INSERVICEYEAR,NAMEPLATECAPACITY,...,MW_WIND,PCT_COAL,PCT_GEOTHERMAL,PCT_HYDROELECTRIC,PCT_NATURAL_GAS,PCT_NUCLEAR,PCT_OIL,PCT_OTHER,PCT_SOLAR,PCT_WIND
0,34,Abbeville City of,1,9798.0,12177.0,3597.0,54037.0,1990,1946,3.700,...,0.0,0.0,0.0,0.234234,0.0,0.0,0.099099,0.0,0.0,0.0
1,84,A & N Electric Coop,2,24338.0,31865.0,9941.0,143500.0,1990,1961,0.225,...,0.0,0.0,0.0,0.000000,0.0,0.0,1.000000,0.0,0.0,0.0
2,150,Adrian Public Utilities Comm,1,2736.0,2311.0,662.0,11587.0,1990,1941,2.000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.500000,0.0,0.0,0.0
3,155,Agralite Coop,2,18405.0,27201.0,5782.0,92809.0,1990,1951,5.000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.200000,0.0,0.0,0.0
4,174,Aitkin Public Utilities Comm,1,5079.0,5049.0,1499.0,25800.0,1990,1930,0.500,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.500000,0.0,0.0,0.0

In [66]:
dum = pd.get_dummies(merged.OWNER_TYPE, prefix='is')
merged_1 = pd.concat([merged, dum],axis=1)
merged_1 = merged_1.drop(columns=['OWNER_TYPE'])
merged_1.head()

,UTILITYCODE,UTILITYNAME,WINTERPEAKDEMAND,SUMMERPEAKDEMAND,TOTALREVENUE,TOTALSALES,DATAYEAR,INSERVICEYEAR,NAMEPLATECAPACITY,MW_COAL,...,PCT_NATURAL_GAS,PCT_NUCLEAR,PCT_OIL,PCT_OTHER,PCT_SOLAR,PCT_WIND,is_0,is_1,is_2,is_3
0,34,Abbeville City of,9798.0,12177.0,3597.0,54037.0,1990,1946,3.700,0.0,...,0.0,0.0,0.099099,0.0,0.0,0.0,0,1,0,0
1,84,A & N Electric Coop,24338.0,31865.0,9941.0,143500.0,1990,1961,0.225,0.0,...,0.0,0.0,1.000000,0.0,0.0,0.0,0,0,1,0
2,150,Adrian Public Utilities Comm,2736.0,2311.0,662.0,11587.0,1990,1941,2.000,0.0,...,0.0,0.0,0.500000,0.0,0.0,0.0,0,1,0,0
3,155,Agralite Coop,18405.0,27201.0,5782.0,92809.0,1990,1951,5.000,0.0,...,0.0,0.0,0.200000,0.0,0.0,0.0,0,0,1,0
4,174,Aitkin Public Utilities Comm,5079.0,5049.0,1499.0,25800.0,1990,1930,0.500,0.0,...,0.0,0.0,0.500000,0.0,0.0,0.0,0,1,0,0

In [67]:
merged_1['TOTALSALES'] = merged_1['TOTALSALES'].replace(to_replace=0, value=1)
merged_1['TOTALREVENUE'] = merged_1['TOTALREVENUE'].replace(to_replace=0, value=1)

In [68]:
# merged_1['UNIQUE_ID'] = str(merged_1['UTILITYCODE']) + '_' + str(merged_1['UTILITYCODE']) + '_' +str(merged_1['UTILITYCODE'])

In [69]:
merged_1.head()

,UTILITYCODE,UTILITYNAME,WINTERPEAKDEMAND,SUMMERPEAKDEMAND,TOTALREVENUE,TOTALSALES,DATAYEAR,INSERVICEYEAR,NAMEPLATECAPACITY,MW_COAL,...,PCT_NATURAL_GAS,PCT_NUCLEAR,PCT_OIL,PCT_OTHER,PCT_SOLAR,PCT_WIND,is_0,is_1,is_2,is_3
0,34,Abbeville City of,9798.0,12177.0,3597.0,54037.0,1990,1946,3.700,0.0,...,0.0,0.0,0.099099,0.0,0.0,0.0,0,1,0,0
1,84,A & N Electric Coop,24338.0,31865.0,9941.0,143500.0,1990,1961,0.225,0.0,...,0.0,0.0,1.000000,0.0,0.0,0.0,0,0,1,0
2,150,Adrian Public Utilities Comm,2736.0,2311.0,662.0,11587.0,1990,1941,2.000,0.0,...,0.0,0.0,0.500000,0.0,0.0,0.0,0,1,0,0
3,155,Agralite Coop,18405.0,27201.0,5782.0,92809.0,1990,1951,5.000,0.0,...,0.0,0.0,0.200000,0.0,0.0,0.0,0,0,1,0
4,174,Aitkin Public Utilities Comm,5079.0,5049.0,1499.0,25800.0,1990,1930,0.500,0.0,...,0.0,0.0,0.500000,0.0,0.0,0.0,0,1,0,0

In [71]:
merged_1.to_csv('../data/combined_cleaned.csv')

In [73]:
y = pd.Series(merged_1['TOTALREVENUE']/merged_1['TOTALSALES']).copy()

In [76]:
ab = np.abs(y.min())
y = y+ab
y

0        0.114035
1        0.116745
2        0.104602
3        0.109769
4        0.105570
           ...
23470    1.047469
23471    1.047469
23472    1.047469
23473    1.047469
23474    1.047469
Length: 23475, dtype: float64